Multiple competitions
semanadeinformatica/website pull request #118
Opened 2023-09-23 02:40 UTC by Naapperas

Closes #98

2023-09-25 10:14 UTC, ttoino requested changes

2023-09-25 10:14 UTC, ttoino commented on app/Http/Middleware/HandleInertiaRequests.php
> +            'competitions' => fn () => $request->input('edition')->competitions ?? [],
Why the `?? []` at the end?

2023-09-25 10:14 UTC, ttoino commented on database/migrations/2023_09_24_230345_add_competition_regulation.php
You could probably merge this migration with the one above

2023-09-25 10:14 UTC, ttoino commented on resources/js/Components/DropdownTrigger.vue
>      >
If this element is clickable, it should be a button, otherwise screen readers will get confused

2023-09-25 10:14 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Create.vue
> +                autofocus
Don't just copy paste please, autofocus is only for the first input

2023-09-25 10:14 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Create.vue
> +                autofocus
Same as above

2023-09-25 10:14 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Create.vue
> +                autofocus
Same as above

2023-09-25 10:14 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Create.vue
> +                autocomplete="registration_link"
This autocomplete value does not exist

2023-09-25 10:14 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Edit.vue
> +                autofocus
Same as above

2023-09-25 10:14 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Edit.vue
> +                autofocus
Same as above

2023-09-25 10:14 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Edit.vue
> +                autocomplete="registration_link"
Same as above

2023-09-25 10:14 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Index.vue
> +                <Header sort-by="theme">Registo</Header>
Careful with the sort-by attribute

2023-09-25 16:04 UTC, Naapperas commented on app/Http/Middleware/HandleInertiaRequests.php
> +            'competitions' => fn () => $request->input('edition')->competitions ?? [],
vvvvv bbbbhmmmmm

2023-09-25 16:04 UTC, Naapperas commented on database/migrations/2023_09_24_230345_add_competition_regulation.php
I will not.

2023-09-25 16:05 UTC, Naapperas commented on resources/js/Components/DropdownTrigger.vue
>      >
:nerd_face:

2023-09-25 16:18 UTC, Naapperas commented
peeper pooper

2023-09-26 10:16 UTC, ttoino approved these changes

2023-09-26 10:18 UTC, pedronunes19 approved these changes
OK

2023-09-26 10:19 UTC, merged

2023-09-26 10:21 UTC, pedrosilva17 approved these changes
LGTM 🚀