Profile page "tickets" and "stickers" implementation
semanadeinformatica/website pull request #120
Opened 2023-09-23 18:06 UTC by toni-santos

Closes #116

2023-09-25 10:23 UTC, ttoino requested changes
Careful with the typescript warnings.

2023-09-25 10:23 UTC, ttoino commented on app/Http/Controllers/SlotCRUDController.php
> +        'name' => 'required|string',
This should also be added to the search array

2023-09-25 10:23 UTC, ttoino commented on resources/js/Components/Profile/InteractionArea.vue
> +
Why did you make this so complicated?

2023-09-25 10:23 UTC, ttoino commented on resources/js/Components/Profile/InteractionArea.vue
> +    </KeepAlive>
Why is KeepAlive needed here?

2023-09-25 12:51 UTC, toni-santos commented on resources/js/Components/Profile/InteractionArea.vue
> +    </KeepAlive>
Whilst it isn't currently necessary, I added it as a precaution for future versions, ones where refreshing the component may break the page. Documentation [here](https://vuejs.org/guide/built-ins/keep-alive.html#basic-usage), for posterity's sake.

2023-09-25 12:51 UTC, toni-santos commented on resources/js/Components/Profile/InteractionArea.vue
> +
This is adapted from what is being done in the program page, it could be reworked, I'll look into it.

2023-09-25 12:59 UTC, toni-santos commented on app/Http/Controllers/SlotCRUDController.php
> +        'name' => 'required|string',
I believe this is already done at the bottom of this file.

2023-09-25 15:47 UTC, Naapperas commented on resources/js/Components/Profile/InteractionArea.vue
> +
This was an idea that we discussed on one of the first meetings: basically the idea is to make the user profile page configurable WTR to what the user can see

2023-09-28 01:52 UTC, Naapperas commented
Don't forget to address all the request changes made.

2023-09-28 01:56 UTC, Naapperas requested changes

2023-09-28 01:56 UTC, Naapperas commented on resources/js/Pages/Profile/Show.vue
> +            id: "ticket",
The key of this object can itself be the id.

2023-09-28 01:56 UTC, Naapperas commented on resources/js/Pages/Profile/Show.vue
> +            id: "sticker",
Same as above

2023-09-28 11:16 UTC, CiscoPr commented
are all the tickets intended to have this color scheme?
![image](https://github.com/semanadeinformatica/website-2023/assets/79597450/c5ff0060-dcf1-40b8-bd62-cd33a2fabca9)

2023-09-28 11:26 UTC, Naapperas commented
> are all the tickets intended to have this color scheme? ![image](https://user-images.githubusercontent.com/79597450/271264712-c5ff0060-dcf1-40b8-bd62-cd33a2fabca9.png)

I believe they are to have differente color schemes based on the event type, that is happening in #113

2023-09-28 13:59 UTC, ttoino approved these changes, later dismissed

2023-09-28 13:59 UTC, ttoino commented on app/Http/Controllers/SlotCRUDController.php
> +        'name' => 'required|string',
You're right

2023-09-28 13:59 UTC, ttoino commented on resources/js/Components/Profile/Ticket.vue
> +                </clipPath>
These can be lifted into TicketWrapper

2023-09-28 23:12 UTC, Naapperas commented
I just found an error that this PR introduces @toni-santos: to reproduce it, go to the profile page and then try to navigate to the profile page again (I used the navbar but I believe this works regardless of the routing): an error is thrown and the page becomes unresponsive. Maybe this is related to dynamically rendering stickers and/or tickets, we need to investigate further...

2023-09-30 12:32 UTC, Naapperas approved these changes

2023-09-30 12:36 UTC, merged