Fix navbar for desktop and mobile
semanadeinformatica/website pull request #129
Opened 2023-09-26 14:11 UTC by toni-santos

Redesign the navbar and fix smaller related issues.

2023-09-27 17:50 UTC, pedronunes19 submitted a review, later dismissed
./format.sh

2023-09-27 17:52 UTC, pedronunes19 commented
Also the previous editions dropdown doesn't seem very intuitive to me compared to previous iterations but I guess it's consistent with other dropdowns

2023-09-27 21:42 UTC, toni-santos commented
This should be ready, we should just check everything with the design team before merging.

2023-09-28 01:51 UTC, Naapperas requested changes
Overall looks good, however the logo seems a little bit too detailed to just be a "side bar element".

Other than that, maybe we should add smooth-scrolling to the website? (most noticeable when accessing home page links)

2023-09-28 01:51 UTC, Naapperas commented on resources/js/Components/HamburgerMenu.vue
> +    }
```suggestion
    document.body.classList.toggle("overflow-hidden");
```

Isn't this a cleaner alternative?

2023-09-28 01:51 UTC, Naapperas commented on resources/js/Components/HamburgerMenu.vue
> +                        class="!w-fit"
Why the `!`?

2023-09-29 01:19 UTC, Naapperas submitted a review, later dismissed

2023-09-29 14:36 UTC, Naapperas approved these changes

2023-09-30 17:52 UTC, merged