Create database schema
semanadeinformatica/website pull request #13
Opened 2023-07-04 02:23 UTC by ttoino

Closes #12.

I created a migration to create all the needed tables.

Still to do:

- [ ] Finish models (right now they are all empty)
- [ ] Add quest unlock conditions
- [ ] Add `onDelete`s and `onUpdate`s to foreign keys
- [ ] Add `CHECK` constraints (if needed)

2023-07-04 02:27 UTC, ttoino commented on database/migrations/2023_07_04_010134_create_schema.php
> +        });
I'm unsure if this is the best way to model these relations, here I'm just making a one to one relationship to the User model (already created before) and each of the user types, but this would allow each user to belong to multiple types and wouldn't let us easily find the user's type in code. An alternative I found is to use Eloquent's polymorphic relationships, but that would require adding two columns to the User model, one for the user type and another for the user type id. If you find other alternatives, feel free to share.

2023-07-04 09:12 UTC, Naapperas requested changes

2023-07-04 09:12 UTC, Naapperas commented on database/migrations/2023_07_04_010134_create_schema.php
> +            $table->enum('category', ['COMPANY', 'TALK', 'WORKSHOP', 'MILESTONE', 'TEAMBUILDING']);
Could you move this list elsewhere? Perhaps the Quest model could have this as a static element, this way we can future-proof this code.

2023-07-04 09:12 UTC, Naapperas commented on database/migrations/2023_07_04_010134_create_schema.php
> +        });
We are missing the `points` attribute in here.

2023-07-04 09:12 UTC, Naapperas commented on database/migrations/2023_07_04_010134_create_schema.php
> +        });
Even though it is a derived attribute, it still should be an attribute, in my opinion.

2023-07-04 13:22 UTC, ttoino commented on database/migrations/2023_07_04_010134_create_schema.php
> +            $table->enum('category', ['COMPANY', 'TALK', 'WORKSHOP', 'MILESTONE', 'TEAMBUILDING']);
I'll look into it, but I doubt it's the best idea since this is a migration and introducing dependencies like that doesn't sound like the best idea

2023-07-04 13:23 UTC, ttoino commented on database/migrations/2023_07_04_010134_create_schema.php
> +        });
Do you think that's the best approach? We can just use the Eloquent ORM to calculate the points

2023-07-04 22:40 UTC, Naapperas commented on database/migrations/2023_07_04_010134_create_schema.php
> +            $table->enum('category', ['COMPANY', 'TALK', 'WORKSHOP', 'MILESTONE', 'TEAMBUILDING']);
I get your point. I just feel like this can bring a lot of trouble in the future due to people forgetting to update the list in both places but honestly I don't have a better idea.

2023-07-04 22:41 UTC, Naapperas commented on database/migrations/2023_07_04_010134_create_schema.php
> +        });
That is true, but I thought that perhaps we should keep track of the points a person acquired over the years. Perhaps we don't, in which case we could just use Eloquent to do that. Its a matter of deciding as a team.

2023-07-18 13:01 UTC, CiscoPr commented on database/migrations/2023_07_04_010134_create_schema.php
> +            $table->morphs('redeemable');
I'm probably nitpicking, but if you're referring to the reward attribute on the Quest table of the UML, shouldn't you also name it as it is in the diagram? Again, it's a really insignificant detail, but still, I think we should remain 100% faithful to the names we gave in the UML
```suggestion
            $table->morphs('reward');
```

2023-07-18 13:08 UTC, ttoino commented on database/migrations/2023_07_04_010134_create_schema.php
> +            $table->morphs('redeemable');
That's not the reward, that's the event/company that needs to be redeemed to unlock the quest, redeemable may not be the best name tho, maybe requirement?

2023-07-18 13:15 UTC, CiscoPr commented on database/migrations/2023_07_04_010134_create_schema.php
> +            $table->morphs('redeemable');
yes, it's a good replacement in my opinion. At least it's a more impartial and straightforward name

2023-07-20 16:26 UTC, Naapperas commented
Take a look at #14 and #15. Those items have high priority (companies are joining on the premise that they will have access to the relevant info) and I believe that they can be implemented by this PR:
- #14 is a matter of adding an attribute for the tiers to the company schema, if I'm not mistaken
- #15 can be implemented through a new table that directly registers company visits or can be implemented through some queries to the *quest* table, we need to see what works best

@ttoino if you can take a look at these when you can, so we can close this PR ASAP and start work on the remaining features.

2023-07-22 14:08 UTC, pedrosilva17 commented
About #15, I believe that introducing a bit of redundancy through a new "visit history" table (as Nuno said) is worth it in this case. Along with it, we could have an on-create trigger in the `enrollment_quest` table, which inserts a row in this new table (perhaps student_id, company_id and timestamps should suffice). 
Instead of running a fairly complex query every time a company manager wants to see who visited them, we pass that load onto the trigger, which runs once every time a quest of that category is completed by a student.

2023-07-23 20:39 UTC, Naapperas commented
Perhaps we should merge this into main already, so other work can be started. Then new PRs targetting the missing features could be made. Thoughts @ttoino ?

2023-07-23 20:49 UTC, Naapperas reviewed
Do the relations on `Edition` and `Enrollment` work? I know there are some "through" variants but I do not see them used anywhere, and from looking at the migration code I do not see some of the relations defined, maybe I am missing something...

2023-07-23 23:27 UTC, ttoino commented
> Perhaps we should merge this into main already, so other work can be started. Then new PRs targetting the missing features could be made. Thoughts @ttoino ?

I think that's a good idea. The requirements for #14 should be done, but I think the requirements for #15 should be added in that issue's PR. Just keep in mind any further additions/modifications to the DB schema should be done in separate migrations, and this one should not be edited after merging.

2023-07-23 23:31 UTC, ttoino commented
> Do the relations on `Edition` and `Enrollment` work? I know there are some "through" variants but I do not see them used anywhere, and from looking at the migration code I do not see some of the relations defined, maybe I am missing something...

I can add some through relations if they are deemed necessary, but I don't think any are missing for the enrollment, we have enrollment \*--1 edition, enrollment \*--1 user, enrollment \*--\* quest (unlocked quests), enrollment \*--\* event (events enrolled in), enrollment \*--\* products (bought products).

2023-07-23 23:34 UTC, Naapperas commented
> > Do the relations on `Edition` and `Enrollment` work? I know there are some "through" variants but I do not see them used anywhere, and from looking at the migration code I do not see some of the relations defined, maybe I am missing something...
> 
> I can add some through relations if they are deemed necessary, but I don't think any are missing for the enrollment, we have enrollment *--1 edition, enrollment *--1 user, enrollment *--* quest (unlocked quests), enrollment *--* event (events enrolled in), enrollment *--* products (bought products).

Oh right, then it's all good.

2023-07-23 23:35 UTC, Naapperas approved these changes
We are just missing some `CHECK`s after this I believe, but great job.

2023-07-24 10:34 UTC, CiscoPr reviewed
Everything looks good me. Very good job @ttoino

2023-07-24 10:34 UTC, CiscoPr commented on app/Models/Enrollment.php
> +     */
Will this fillable array have any attributes at all?

2023-07-24 10:35 UTC, CiscoPr commented on app/Models/Enrollment.php
> +    ];
will this fillable array have any attributes at all?

2023-07-24 14:09 UTC, merged