Shop
semanadeinformatica/website pull request #132
Opened 2023-09-26 15:27 UTC by toni-santos

Closes #131

2023-09-26 19:47 UTC, Naapperas requested changes

2023-09-26 19:47 UTC, Naapperas commented on resources/js/Components/Shop/ShopItem.vue
> +}
We already have the Product type: you should use that, even when mocking.

2023-09-26 19:47 UTC, Naapperas commented on resources/js/Pages/Shop.vue
> +},]
Same as above.

2023-09-28 01:29 UTC, Naapperas requested changes
There is no way for a user to go to the shop unless they know the exat Url, maybe a link in the Navbar?

2023-09-28 01:29 UTC, Naapperas commented on app/Http/Controllers/ShopController.php
> +        $products = Product::where('edition_id', $edition->id)->get();
```suggestion
        $products = $edition->products;
```

This is more idiomatic, in my opinion.

2023-09-28 01:29 UTC, Naapperas commented on app/Http/Controllers/ShopController.php
> +        $products = Product::where('edition_id', $edition->id)->get();
You could even inline this in the return value

2023-09-28 01:29 UTC, Naapperas commented on resources/js/Components/Shop/ShopItem.vue
Are you going to implement buying items? Nonetheless, we should already have a button for that. If you have other ideas please share them.

2023-09-30 17:25 UTC, Naapperas submitted a review, later dismissed

2023-09-30 17:33 UTC, pedronunes19 commented
> There is no way for a user to go to the shop unless they know the exact Url, maybe a link in the Navbar?

Was this fixed?

2023-09-30 17:39 UTC, Naapperas commented
> > There is no way for a user to go to the shop unless they know the exact Url, maybe a link in the Navbar?
> 
> Was this fixed?

I believe it was, but if it was not request for that to be changed.

2023-09-30 17:44 UTC, toni-santos commented
> > > There is no way for a user to go to the shop unless they know the exact Url, maybe a link in the Navbar?
> > 
> > 
> > Was this fixed?
> 
> I believe it was, but if it was not request for that to be changed.

This hasn't been addressed has #129 introduces an altered navbar and hasn't been merged.

2023-09-30 18:06 UTC, pedronunes19 approved these changes

2023-09-30 19:17 UTC, merged