Edit profile page structure, based on Laravel's
semanadeinformatica/website pull request #136
Opened 2023-09-26 23:52 UTC by pedrosilva17

Closes #108 
Currently similar to the default edit profile page from Laravel, now in a different route. The sentences in here need to be added to #75 (I can do that after this is merged, if you want @Naapperas)

![image](https://github.com/semanadeinformatica/website-2023/assets/75742355/348765d2-345e-4875-8798-932f62d6298a)

![image](https://github.com/semanadeinformatica/website-2023/assets/75742355/6c9432c4-288c-4566-9309-c44824599fb5)

![image](https://github.com/semanadeinformatica/website-2023/assets/75742355/7a6834ad-9fb8-44d4-b868-ada108237fb4)

2023-09-28 01:46 UTC, Naapperas requested changes
Please be careful with the amount of `div`s you use. Ask @ttoino if you have any doubts regarding that matter.

2023-09-28 01:46 UTC, Naapperas commented on resources/js/Pages/Profile/Edit.vue
> +            <div class="mx-auto max-w-7xl py-10 sm:px-6 lg:px-8">
I believe `7xl` is a lot in this case: `2xl` or `3xl` should be enough.

2023-09-30 14:59 UTC, Naapperas submitted a review, later dismissed

2023-09-30 17:18 UTC, Naapperas commented
@pedrosilva17 one thing I noticed: perhaps we could make the font of this page's text bold, or at least make it stand out more.

2023-09-30 20:24 UTC, Naapperas approved these changes

2023-09-30 20:47 UTC, toni-santos approved these changes

2023-09-30 21:06 UTC, merged