Added initial backend code for event registration
semanadeinformatica/website pull request #139
Opened 2023-09-28 11:23 UTC by Naapperas

Closes #43

2023-09-28 21:01 UTC, toni-santos requested changes
This is great! Few changes needed.

2023-09-28 21:01 UTC, toni-santos commented on resources/js/Pages/Event.vue
> +            <PrimaryButton
This is missing a flex and a column orientation

2023-09-28 21:01 UTC, toni-santos commented on app/Http/Controllers/EventController.php
> +    }
When I attempted to sign up for an event with an account that has no enrollment I got a "No enrollment screen", we could maybe use laravel's banner to display this alert and redirect the user to the home page.

2023-09-28 21:24 UTC, Naapperas commented on app/Http/Controllers/EventController.php
> +    }
The other option is to disable the user from even issuing this request if they are not enrolled, what do you think? Your way is definitely simpler to implement

2023-09-28 21:28 UTC, toni-santos commented on app/Http/Controllers/EventController.php
> +    }
While not allowing the user at all to sign up for the event may seem more intuitive it can also be confusing. Imo, the banner method acts as a reminder as to how things work. A message reminding them that they must sign up for the edition should suffice and point them in the right direction. Further more, if people find that they aren't able to find where to sign up we can also add a "scroll to bottom" type button on the homepage, only if that manifests itself as a problem.

2023-09-28 22:37 UTC, Naapperas commented
This should only be merged after #116

2023-09-29 08:00 UTC, ttoino commented on app/Http/Controllers/EventController.php
> +    }
I think the best UX wouldn't show an error, that makes the user think they did something wrong. Imo, we shouldn't ever show an action that the user can't take. In this case we should show a button to enroll in the edition.

2023-09-29 08:02 UTC, toni-santos commented on app/Http/Controllers/EventController.php
> +    }
I didn't consider showing a button for sign up on the edition, that's a good idea.

2023-09-29 11:33 UTC, toni-santos submitted a review, later dismissed

2023-09-30 13:47 UTC, toni-santos approved these changes

2023-09-30 13:50 UTC, merged