Add backend for quests
semanadeinformatica/website pull request #145
Opened 2023-10-02 01:02 UTC by ttoino

2023-10-02 02:51 UTC, Naapperas submitted a review, later dismissed

2023-10-03 21:42 UTC, Naapperas requested changes

2023-10-03 21:42 UTC, Naapperas commented on app/Http/Controllers/EventController.php
> +            return redirect()->back()->dangerBanner('Não podes inscrever-se neste evento');
```suggestion
            return redirect()->back()->dangerBanner('Não podes inscrever-te neste evento');
```

2023-10-03 21:42 UTC, Naapperas commented on app/Http/Controllers/QuestController.php
> +        return redirect()->back()->banner('Quest atribuída com sucesso!');
Beware of text translations.

2023-10-03 21:42 UTC, Naapperas commented on app/Providers/AuthServiceProvider.php
> +                    $user->isAdmin() && // user is admin and either
Shouldn't this allow for staff to perform this action?

2023-10-05 00:49 UTC, ttoino commented on app/Providers/AuthServiceProvider.php
> +                    $user->isAdmin() && // user is admin and either
Yes, but that's a little hard right now, we should do that in a bigger PR so staff have all the necessary permissions.

2023-10-05 00:50 UTC, ttoino commented on app/Http/Controllers/QuestController.php
> +        return redirect()->back()->banner('Quest atribuída com sucesso!');
We're not translating any banners right now, maybe #75 can handle that

2023-10-05 00:50 UTC, ttoino commented on app/Http/Controllers/EventController.php
> +            return redirect()->back()->dangerBanner('Não podes inscrever-se neste evento');
You're right, mb

2023-10-05 01:27 UTC, Naapperas approved these changes

2023-10-05 01:29 UTC, merged