Fix team page
semanadeinformatica/website pull request #149
Opened 2023-10-02 08:26 UTC by toni-santos

Remove the border on the team page, and other tweaks.

2023-10-02 16:47 UTC, Naapperas requested changes
LGTM

2023-10-02 16:47 UTC, Naapperas commented on resources/js/Components/Navbar.vue
You should add `preserve-state` to the Link component in DropdownLink. It will fix the page reload problem where a smooth-scroll "starts from scratch".

2023-10-02 16:47 UTC, Naapperas commented on resources/js/Pages/Home.vue
> +            Inscreve-te<v-icon name="io-chevron-down" fill="white"></v-icon>
This icon should be an arrow, this might confuse people into thinking this is a dropdown.

2023-10-03 09:37 UTC, pedronunes19 approved these changes, later dismissed

2023-10-03 16:43 UTC, Naapperas approved these changes

2023-10-03 16:48 UTC, merged