Simple file upload proof of concept
semanadeinformatica/website pull request #16
Opened 2023-08-04 18:49 UTC by pedrosilva17

This PR implements a file upload system to use for CVs and potentially other stuff in the future.

Currently, it is very basic and one-dimensional, merely serving as a test to verify that the file uploads are handled correctly.

The idea is to create a generic middleware which will take care of redirecting to the appropriate controller, as well as making use of Jetstream Actions. The message I've sent on Slack is relevant to this, with an article and a video regarding the suggested approach to be adopted. Leave your suggestions below if you think of other ways to do this.

2023-08-07 23:02 UTC, Naapperas commented
Can you elaborate on what you mean by "redirecting to the appropriate controller"?

2023-08-07 23:16 UTC, pedrosilva17 commented
I typed that after seeing this section of the Laravel documentation: https://laravel.com/docs/10.x/redirects#redirecting-controller-actions
With that being said, I've since explored a bit more of the available options and decided that the better approach would be following the steps I explained in the Slack thread, since it incorporates our needs in the already established code from Fortify and Jetstream. What do you think? I still have to test it and verify that it does work, but I currently don't see where it could go wrong.

2023-08-08 19:13 UTC, pedrosilva17 commented
CV support is pratically done. I tried to utilize the already established Fortify and Jetstream classes/methods as much as possible and expand them where needed. 
In my last commit, some temporary changes to schemas were made in order to fix an ongoing problem (being unable to create new accounts), but shouldn't be considered valid solutions and will be reverted when merging. In that same commit, I modified the default frontend to enable CV upload for testing, so please feel free to do so.
Currently there's only one route for downloads, but that could change, since we might need to specify different storage disks depending on the type of file we're downloading (the name of the storage disk is hardcoded in the test frontend, at the moment).
As usual, leave your suggestions/fixes below, I still believe there could be room for improvement.

2023-08-08 19:22 UTC, Naapperas requested changes

2023-08-08 19:22 UTC, Naapperas commented on app/Traits/HasCV.php
> +        return isset($_ENV['VAPOR_ARTIFACT_NAME']) ? 's3' : config('jetstream.cv_disk', 'public');
We are neither using Vapor or AWS S3 buckets, should this be here?

2023-08-08 19:22 UTC, Naapperas commented on routes/jetstream.php
> +        Route::delete('/user/cv', [CVController::class, 'destroy'])
I believe we should have a route group for the CV. Also, the `user` routes could make use of route parameters, maybe I'm jumping to conclusions but I see none.

2023-08-08 19:22 UTC, Naapperas commented on routes/api.php
> +Route::get('/download', [FileController::class, 'download'])->name('file.download');
I believe that downloads can already be handled by the browser, is this needed?

2023-08-08 19:25 UTC, pedrosilva17 commented on app/Traits/HasCV.php
> +        return isset($_ENV['VAPOR_ARTIFACT_NAME']) ? 's3' : config('jetstream.cv_disk', 'public');
Could be useful in case we add remote storage capabilities, isn't needed for now though

2023-08-08 19:33 UTC, pedrosilva17 commented on routes/jetstream.php
> +        Route::delete('/user/cv', [CVController::class, 'destroy'])
These are the default jetstream routes (excluding the CV part). But yes, we would need to pass parameters to the routes if we want to access other user profiles

2023-08-08 19:57 UTC, pedrosilva17 commented on routes/api.php
> +Route::get('/download', [FileController::class, 'download'])->name('file.download');
I use that route to generate the response for downloading the file in the browser (with Laravel's `Storage::download()`). Is there a cleaner way of generating that response, passing the file storage url, using only the browser?

2023-08-08 20:08 UTC, Naapperas commented on app/Traits/HasCV.php
> +        return isset($_ENV['VAPOR_ARTIFACT_NAME']) ? 's3' : config('jetstream.cv_disk', 'public');
Oh ok, like some cloud provider. Forgot that, nice catch. The only catch I can ser with this approach (which could be easily fixable) os if the provider we choose has a custom PHP SDK, in which case these would not be needed.

2023-08-08 20:09 UTC, Naapperas commented on routes/jetstream.php
> +        Route::delete('/user/cv', [CVController::class, 'destroy'])
Perhaps these needs a dedicated discussion just on this topic, Will leave for later.

2023-08-08 20:11 UTC, Naapperas commented on routes/api.php
> +Route::get('/download', [FileController::class, 'download'])->name('file.download');
I think that browsers can already handle URI's that refer to files, either for downloading or displaying, but I'm not entirely certain. We need to investigate further.

2023-09-02 09:50 UTC, CiscoPr commented on database/migrations/2023_07_04_010134_create_schema.php
>          // User tables
Everything lgtm, but i have a question: won't there be any problem by eliminating the **users** table that was here?

2023-09-02 10:51 UTC, pedrosilva17 commented on database/migrations/2023_07_04_010134_create_schema.php
>          // User tables
I completely forgot to add that back after testing, my bad

2023-09-02 12:34 UTC, pedrosilva17 commented
Now sure what's up with the tests - some easy ones fail, like rendering the registration page or creating a new account, but I can do that just fine in my local branch.

2023-09-03 07:50 UTC, ttoino requested changes

2023-09-03 07:50 UTC, ttoino commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('cv_path', 2048)->nullable();
Migrations should not be modified after they are merged, this is because the website could already be in production and we would not be able to run all migrations from the start, this should be separated into a new migration.

2023-09-03 07:50 UTC, ttoino commented on database/migrations/2023_07_04_010134_create_schema.php
> -        });
Same as above

2023-09-03 07:50 UTC, ttoino commented on database/migrations/2023_08_04_183516_create_resumes_table.php
> +        });
Why is a separate table required for the resumes? Isn't it already an attribute in the user model?

2023-09-03 07:50 UTC, ttoino commented on app/Providers/JetstreamServiceProvider.php
> +        Jetstream::ignoreRoutes();
What does this do?

2023-09-03 07:50 UTC, ttoino commented on app/Providers/FortifyServiceProvider.php
> +        Fortify::ignoreRoutes();
Same as above

2023-09-03 07:50 UTC, ttoino commented on .env
> +#APP_URL=http://localhost
Why was this commented?

2023-09-03 07:50 UTC, ttoino commented on routes/api.php
> +Route::get('/download', [FileController::class, 'download'])->name('file.download');
This route is not protected, this could lead anyone to another user's cv I think

2023-09-03 07:51 UTC, ttoino commented on app/Providers/JetstreamServiceProvider.php
> +        Jetstream::ignoreRoutes();
Nevermind, I got it

2023-09-03 07:57 UTC, pedrosilva17 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('cv_path', 2048)->nullable();
You're right, my mistake

2023-09-03 07:58 UTC, pedrosilva17 commented on database/migrations/2023_08_04_183516_create_resumes_table.php
> +        });
This is outdated code from my first attempt at implementing file uploads. I'll clean it up when I return

2023-09-03 07:58 UTC, pedrosilva17 commented on .env
> +#APP_URL=http://localhost
No clue, honestly, I'll change it back

2023-09-05 23:58 UTC, ttoino commented
Any updates on this PR? Work here will unlock work on other issues where user routes are needed, such as #41 and #43

2023-09-06 04:45 UTC, pedrosilva17 commented
I will not be home until 7th September at night, so I can't work on this at the moment. If it is urgent, someone else can apply the required changes, otherwise I will do it as soon as possible.

2023-09-12 03:11 UTC, Naapperas commented
@pedrosilva17 What's missing in this PR? The changes you made here are important to other issues so it's important to have this one merged as soon as possible.

2023-09-12 11:07 UTC, pedrosilva17 commented
@CiscoPr has suggested we make these changes (the ones in regards to CVs) in the Student table instead of the User, which would require more work but would make the interactions with Companies and Students easier when joining stuff (regarding visits, CVs, etc.). What do you think @Naapperas ?

2023-09-12 13:23 UTC, Naapperas commented
> @CiscoPr has suggested we make these changes (the ones in regards to CVs) in the Student table instead of the User, which would require more work but would make the interactions with Companies and Students easier when joining stuff (regarding visits, CVs, etc.). What do you think @Naapperas ?

Sure, go ahead.

2023-09-12 17:18 UTC, ttoino commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->morphs('usertype');
This migration should not be modified

2023-09-12 17:23 UTC, pedrosilva17 commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->morphs('usertype');
Forgot to revert that change, thanks 👍

2023-09-13 13:04 UTC, Naapperas requested changes
I left a lot of comments on this one.

Perhaps we should drop the whole "generic file upload" thing and just focus on the CVs for now. I believe it would not be that big of a change to make, simply deleting the `FileController` and moving some methods and routes around. This way we can close this PR for good and advance the site's backend.

Comments? @ttoino @toni-santos @pedrosilva17 @CiscoPr @diogofonte @pedronunes19

2023-09-13 13:04 UTC, Naapperas commented on app/Actions/Fortify/UpdateUserProfileInformation.php
> +            'cv' => ['nullable', 'mimes:pdf', 'max:4096'],
Please take a look at the documentation [here](https://laravel.com/docs/10.x/validation#validating-files) and see what is the best way to define these rules.

2023-09-13 13:04 UTC, Naapperas commented on app/Actions/Fortify/UpdateUserProfileInformation.php
> +            $student = Student::where('user_id', $user->id)->first();
```suggestion
            $student = Student::find($user->id);
```

This uses the primary key directly, whatever it may be. I believe it's a better way of doing this but feel free to ignore.

2023-09-13 13:04 UTC, Naapperas commented on app/Traits/HasCV.php
> +        return isset($_ENV['VAPOR_ARTIFACT_NAME']) ? 's3' : config('jetstream.cv_disk', 'public');
@pedrosilva17 we will be storing images and files on our hardware so we won't need any cloud provider,, I'll leave it up to you to change this line (or not) and mark this conversation as resolved.

2023-09-13 13:04 UTC, Naapperas commented on app/Models/Student.php
> +    }
This method is not used anywhere, please remove it.

2023-09-13 13:04 UTC, Naapperas commented on app/Traits/HasCV.php
> +        tap($this->cv_path, function ($previous) use ($cv, $storagePath) {
Why did you use `tap()` here?

2023-09-13 13:04 UTC, Naapperas commented on app/Traits/HasCV.php
> +            }
This should not be here: semantically an update is not a creation action.

2023-09-13 13:04 UTC, Naapperas commented on app/Traits/HasCV.php
> +            }
Eitherway, I believe that this, if it is to stay in this method, should happen before we store the new file.

2023-09-13 13:04 UTC, Naapperas commented on app/Traits/HasCV.php
> +                    $storagePath, ['disk' => $this->CVDisk()]
The documentation I found did not speak of having an array as an argument, does this work as it should?

2023-09-13 13:04 UTC, Naapperas commented on app/Traits/HasCV.php
> +     * Update the student's CV.
In this case it is the students' CVs, but I believe this comment should be more generic.

2023-09-13 13:04 UTC, Naapperas commented on routes/api.php
> +Route::middleware('auth:sanctum')->get('/download', [FileController::class, 'download'])->name('file.download');
Why are we doing this through an API call? API support isn't enabled yet so this should be based on the web router.

2023-09-13 13:04 UTC, Naapperas commented on routes/jetstream.php
> +        Route::delete('/user/cv', [CVController::class, 'destroy'])
Coming back to this comment. Even though we are manually adding routes in order to have control over the route paths, we should not change these files any further. We should use the `web.php` file for any web related route.

2023-09-13 13:04 UTC, Naapperas commented on app/Models/Resume.php
This class is not used anywhere, it should be removed.

2023-09-13 13:04 UTC, Naapperas commented on routes/api.php
> +Route::middleware('auth:sanctum')->get('/download', [FileController::class, 'download'])->name('file.download');
In my opinion, we should have a route that is like `/user/cv/download` and that is the one that triggers the download.

2023-09-13 13:04 UTC, Naapperas commented on routes/jetstream.php
> +        Route::delete('/user/cv', [CVController::class, 'destroy'])
Also, companies need to be able to see users that have visited them, so we should still have a route group for that.

2023-09-13 13:04 UTC, Naapperas commented on app/Http/Controllers/FileController.php
> +        return $this->downloadFromUrl($request->url, $request->storageDisk);
I think we should assume for now that the storage disk will always the `public` disk. If not, we should use the configuration used for storing them, instead of relying on the request. Food for thought.

2023-09-13 13:04 UTC, Naapperas commented on app/Traits/ProcessesFiles.php
> +        return Storage::disk($storageName)->download($url);
Same as above.

2023-09-13 13:04 UTC, Naapperas commented on app/Http/Controllers/CVController.php
I'm not really fond of having a whole controller just to delete CVs, even if that is what Jetstream is doing.

2023-09-13 13:07 UTC, Naapperas commented
Also, if it is needed just ignore the tests. Other than that, some cleaning should be made to the commits.

2023-09-13 13:33 UTC, Naapperas commented
I'm at a loss regarding the tests. Unless someone figures this out we are probably going to have to ignore them.

2023-09-13 13:45 UTC, pedrosilva17 commented on app/Traits/HasCV.php
> +        tap($this->cv_path, function ($previous) use ($cv, $storagePath) {
At first I thought it would be more useful, but all it does is avoid writing `$previous = $this->cv_path` in a separate line.

2023-09-13 13:46 UTC, pedrosilva17 commented on app/Traits/HasCV.php
> +                    $storagePath, ['disk' => $this->CVDisk()]
This was adapted directly from the `HasProfilePhoto.php` file in Jetstream, which deals with profile pictures.

2023-09-13 13:53 UTC, Naapperas commented
And don't forget to rebase with `main`.

2023-09-13 15:34 UTC, Naapperas commented on routes/jetstream.php
> +        Route::delete('/user/cv', [CVController::class, 'destroy'])
This is done in #48

2023-09-13 15:44 UTC, Naapperas requested changes
Please leave a comment in the Jestream and Fortify files (and Providers aswell) explaining why we have that code in place.

2023-09-13 15:44 UTC, Naapperas commented on routes/web.php
> +    Route::get('/user/cv/download', [FileController::class, 'download'])->name('file.download');
We should make use of [route groups](https://laravel.com/docs/10.x/routing#route-groups), makes the code cleaner: I suggest a group for the users and a group for CVs.

2023-09-13 15:44 UTC, Naapperas commented on app/Actions/Jetstream/DeleteUser.php
> +        }
I believe it would be best if the model came from the `morph` relationship instead of calling `Student::where`.

2023-09-13 23:56 UTC, Naapperas submitted a review, later dismissed

2023-09-13 23:56 UTC, Naapperas commented
Don't forget to rebase

2023-09-14 00:03 UTC, Naapperas commented
> Don't forget to rebase

By doing this you can also tackle the comment that's left.

2023-09-14 10:46 UTC, ttoino submitted a review, later dismissed

2023-09-14 10:46 UTC, ttoino commented on app/Actions/Fortify/UpdateUserProfileInformation.php
> +            'cv' => ['nullable', File::types(['pdf'])->max(4 * 1024)],
Is this maximum size in bytes or another unit? If it's in bytes I'm not sure that's enough, as my CV takes up about 500KB

2023-09-14 10:46 UTC, ttoino commented on app/Actions/Jetstream/DeleteUser.php
> +        }
These docs may be helpful here: https://laravel.com/docs/10.x/eloquent-relationships#querying-morph-to-relationships

2023-09-14 11:19 UTC, Naapperas commented on app/Actions/Fortify/UpdateUserProfileInformation.php
> +            'cv' => ['nullable', File::types(['pdf'])->max(4 * 1024)],
@pedrosilva17 according to [this](https://laravel.com/docs/10.x/validation#validating-files-file-sizes) you can specify the units directly to the validator. Makes it more readable.

2023-09-14 11:21 UTC, Naapperas commented
Don't forget to rebase

2023-09-14 14:18 UTC, ttoino approved these changes

2023-09-14 14:23 UTC, Naapperas approved these changes

2023-09-14 14:29 UTC, merged