Student history
semanadeinformatica/website pull request #22
Opened 2023-08-08 12:05 UTC by CiscoPr

Closes #15 
A separate migration updates the new table **visit_history**  based on the values from the newly inserted row in the **enrollment_quest** table, including the corresponding **student_id**, **company_id**, and **timestamps**

2023-08-08 19:22 UTC, diogofonte submitted a review, later dismissed
Looks good to me!

2023-08-13 20:47 UTC, pedronunes19 requested changes
This seems to achieve our goal, not sure if anything else is needed in the context of this PR

2023-08-13 20:47 UTC, pedronunes19 commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                        VALUES (NEW.student_id, (
doesn't enrollment_quest have an enrollment_id instead? the overall solution seems to work, that detail just propped some questions

2023-08-15 14:29 UTC, CiscoPr commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                        VALUES (NEW.student_id, (
Yes, you're absolutely right, that detail didn't even cross my mind. I will correct it asap

2023-08-15 17:11 UTC, CiscoPr commented
Now, although the student_id is finally selected correctly, i came across another mistake on my part when it comes to the company_id, which is not properly retrieved

2023-08-15 18:11 UTC, CiscoPr commented
The **company_id** should also be correctly retrieved now. The previous solution was wrong, since the id of the quests table did **not** correspond to the id's of the companies. 
Right now, what I do is to work with the **polymorphic relationship** "requirement" of the quests table and, if it points to the **Company** model, I select its id.

2023-08-15 21:15 UTC, pedronunes19 submitted a review, later dismissed
LGTM

2023-08-21 16:55 UTC, pedronunes19 submitted a review, later dismissed

2023-08-28 18:05 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +    }
Is this enough? Is dropping the trigger not required?

2023-08-29 09:25 UTC, CiscoPr commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +    }
i don't think so. I think the trigger will be constantly updated everytime the migration is run. Not 100% sure tho

2023-08-31 21:54 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +    }
I checked our other migration, and the function `update_visit_history` should also be dropped here. It's not that bad if it isn't, as you're creating it only if it doesn't exist, but all migrations should be self contained and completely reversible.

2023-09-01 09:48 UTC, CiscoPr commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +    }
Makes sense. I will change it then, thanks for your feedback

2023-09-01 20:03 UTC, ttoino approved these changes, later dismissed

2023-09-01 20:18 UTC, pedronunes19 approved these changes, later dismissed

2023-09-02 10:33 UTC, CiscoPr commented
I added the cv_path to the trigger, even tho this will only fully make sense when the PR corresponding to the [file uploading](https://github.com/semanadeinformatica/website-2023/pull/16) is merged

2023-09-02 16:51 UTC, CiscoPr commented
Right now, all checks are passing, but, for some reason, while running the tests, there's the following error:
`  SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "IF"
LINE 6:                     IF (NEW IS NOT NULL) THEN`

2023-09-02 17:17 UTC, CiscoPr commented
This problem should now be solved

2023-09-05 21:01 UTC, ttoino requested changes
I've left some comments on the trigger function, if it works then it is good for now but I believe it could/should be improved in order to not have slow running code on the DB: I thought this up in a hurry but I believe you can implement this using only one insert, more `JOIN`s and more complex conditions (for requirement types and company tiers).

Ass: @Naapperas

2023-09-05 21:01 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                                INSERT INTO visit_history (student_id, company_id, cv_path, created_at, updated_at)
Why do you insert a `cv_path` here when there is no such attribute in the table definition?
Maybe this was forgotten but this will give rise to issues in the future when this trigger runs this function.

2023-09-05 21:01 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                                            ELSE NULL
Since you are reusing the same value here it could be extracted to a variable.

2023-09-05 21:01 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                                    u.cv_path,
`cv_path` belongs to the Student, not the User

2023-09-05 21:01 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                                            ELSE NULL
Inserting `NULL` here will cause errors since you defined the foreign key to be constrained by the DB (aka it cannot be `NULL`).

One solution is to see if the requirement type refers to a company and only then you insert anything.

2023-09-05 21:01 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +            CREATE TRIGGER update_visit_history
Just for safety, I believe we should include a `IF NOT EXISTS` clause when creating the trigger.

2023-09-05 21:01 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                            LEFT JOIN companies c ON q.requirement_type = \'\App\Models\Company\' AND q.requirement_id = c.id
You get the tier for a company because the requirement type specifies that this quest referred to a company, but then you re(dundantly)-check the requirement type again.

2023-09-05 21:01 UTC, ttoino commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +            CREATE TRIGGER update_visit_history
First confirm if this is even possible.

2023-09-06 10:04 UTC, CiscoPr commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                                INSERT INTO visit_history (student_id, company_id, cv_path, created_at, updated_at)
Yes, i only noticed this mistake on my part during the group meeting on monday, sorry about that

2023-09-06 10:09 UTC, CiscoPr commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                                    u.cv_path,
Yes, ideally that's the case. I just got confused on the PR #16 so i put in the user.
Also, @toni-santos and @pedronunes19 also mentioned something important: since we already have the `student_id` in here (and by correcting the usage of the `cv_path` in the **File Upload** PR in order for it to belong to the student instead of the user) adding the column of the cv becomes a bit useless, don't you think so? The reason being that, by having the student id, the company will already have access to the cv of the student

2023-09-06 16:11 UTC, CiscoPr commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                                            ELSE NULL
~~could you be more specific please?~~
nvm this, i think i got it

2023-09-12 03:20 UTC, Naapperas commented
@CiscoPr I have opened a [PR](#50) that may affect your trigger function, beware of that.

2023-09-12 15:01 UTC, CiscoPr commented
> @CiscoPr I have opened a [PR](https://github.com/semanadeinformatica/website-2023/pull/50) that may affect your trigger function, beware of that.

Okay, i will check it out then

2023-09-13 22:45 UTC, CiscoPr commented
@Naapperas Just to make sure i understood correctly the sugestion you made [here](https://github.com/semanadeinformatica/website-2023/pull/22#discussion_r1316395289), is this what you were talking about? 
```
DECLARE q_ids TEXT;
DECLARE company_type TEXT;
```
```
q_ids := \'FROM quests WHERE id = NEW.quest_id\';
company_type := \'\App\Models\Company\';
```
```
SELECT requirement_type q_ids ) = company_type THEN (SELECT requirement_id q_ids)
```
Btw, these changes still don't take care of [this](https://github.com/semanadeinformatica/website-2023/pull/22#discussion_r1316396952) problem... i will look into it now

2023-09-14 11:38 UTC, CiscoPr commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +            CREATE TRIGGER update_visit_history
I searched a bit and tested it out, but it seems like it is impossible to do this. I tested it out and it even prints out a ```SYNTAX ERROR```

2023-09-14 11:54 UTC, Naapperas commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +            CREATE TRIGGER update_visit_history
`CREATE OR REPLACE` is what I was looking for. It is not that important thought, hoorah migrations.

2023-09-14 11:59 UTC, Naapperas requested changes
Almost there.

2023-09-14 11:59 UTC, Naapperas commented on database/migrations/2023_08_05_121302_add_oncreate_trigger_enrollment_quest.php
> +                                    v_company_id,
This suffers from the same problem I mentioned: if the requirement is not met, you are inserting the default value of `v_company_id` (which I assume is `NULL`) into the table, leading to the same issue I talked about. What you should do is a check similar to what you do for the company tier.

2023-09-14 14:23 UTC, ttoino approved these changes

2023-09-14 17:50 UTC, pedronunes19 approved these changes

2023-09-14 18:46 UTC, Naapperas approved these changes
LGTM! Amazing work @CiscoPr  :two_hearts: :two_hearts::two_hearts:  

Thank very much you @ttoino and @pedronunes19 for reviewing this PR :heart_eyes:

2023-09-14 18:56 UTC, merged