Add quest qr code
semanadeinformatica/website pull request #225
Opened 2023-10-20 17:19 UTC by ttoino

2023-10-20 17:28 UTC, Naapperas requested changes

2023-10-20 17:28 UTC, Naapperas commented on app/Http/Controllers/UserController.php
> +            if (Participant::where('quest_code', $code)->exists()) {
Please add a comment explaining this: it should mention that the qr code is unique on the participant

2023-10-20 17:28 UTC, Naapperas commented on resources/js/Components/Profile/InfoCard.vue
> +            <ModalsContainer></ModalsContainer>
Isn't this already rendered by the AppLayout?

2023-10-21 01:14 UTC, pedronunes19 submitted a review, later dismissed
squash commit

2023-10-21 15:56 UTC, CiscoPr approved these changes

2023-10-21 16:07 UTC, pedrosilva17 approved these changes

2023-10-21 20:44 UTC, Naapperas approved these changes
LGTM

2023-10-21 20:57 UTC, merged