Auth pages
semanadeinformatica/website pull request #23
Opened 2023-08-08 13:55 UTC by ttoino

Implements and styles the authentication pages (login, register, recover password, etc.)

2023-08-08 18:50 UTC, Naapperas requested changes

2023-08-08 18:50 UTC, Naapperas commented on resources/js/Components/Checkbox.vue
> +        class="border border-black checked:border-black checked:hover:border-black bg-2023-bg hover:shadow shadow-2023-orange checked:bg-2023-teal checked:hover:bg-2023-teal-dark outline-none transit
Aren't some of these classes redundant? Namely the ones referring to the border.

2023-08-08 18:50 UTC, Naapperas commented on resources/js/Pages/Auth/Login.vue
> +                <span class="text-2023-teal">Remember me</span>
This text should be in Portuguese, to match the rest of the page.

2023-08-08 18:50 UTC, Naapperas commented on tailwind.config.js
> +            },
The color palette should be configurable outside of this file, so that future developers have an easier experience adapting their version of the website.

2023-08-08 18:50 UTC, Naapperas commented on tailwind.config.js
> +    })],
I don't know if I'm too confortable with these options being hard-coded for the same reason I expressed above: they may make sense for the design of this year's edition but not for the next one. I will write a separate issue for that but please keep that in mind.

2023-08-08 18:50 UTC, Naapperas commented on tailwind.config.js
> +            },
I believe this can already be updated on this PR, since it's a relatively small fix.

2023-08-08 18:57 UTC, ttoino commented on resources/js/Components/Checkbox.vue
> +        class="border border-black checked:border-black checked:hover:border-black bg-2023-bg hover:shadow shadow-2023-orange checked:bg-2023-teal checked:hover:bg-2023-teal-dark outline-none transit
No, `border-black` only sets the border color, while `border` sets the border to be 1px wide and gray

2023-08-08 19:14 UTC, Naapperas commented on resources/js/Components/Checkbox.vue
> +        class="border border-black checked:border-black checked:hover:border-black bg-2023-bg hover:shadow shadow-2023-orange checked:bg-2023-teal checked:hover:bg-2023-teal-dark outline-none transit
Oh ok, kinda sucks to have the same class name repeated but it is what it is.

2023-08-15 15:48 UTC, ttoino commented on tailwind.config.js
> +            },
In an effort to keep this pr small, I think this should be explored in a separate issue that tries to make all the styles generic enough to be different for different editions.

2023-08-15 16:49 UTC, Naapperas approved these changes

2023-08-15 16:56 UTC, pedronunes19 approved these changes

2023-08-15 17:02 UTC, merged