Maintenance page
semanadeinformatica/website pull request #25
Opened 2023-08-08 18:31 UTC by toni-santos

Closes #24

2023-08-08 19:13 UTC, Naapperas requested changes

2023-08-08 19:13 UTC, Naapperas commented on app/Exceptions/Handler.php
> +        if (in_array($response->status(), [500, 404, 403])) {
Why is this array special? What is the meaning of those error codes?

2023-08-08 19:13 UTC, Naapperas commented on app/Exceptions/Handler.php
> +        if (in_array($response->status(), [500, 404, 403])) {
All this to say, try not no use too many magic constants :)

2023-08-08 19:13 UTC, Naapperas commented on app/Exceptions/Handler.php
> +        }
Is this here because we are overriding the default handler? One would think that this could be done automatically. Also, are there other ways of handling error requests? Like appending an additional handler to a "stack" of handler? This way we could preserve this file and do things in a more `Laravel`-ish way. If there is no other way then that's fine.

2023-08-08 19:13 UTC, Naapperas commented on resources/js/Pages/Error.vue
> +})
These could be made into one single `computed` call that returns an object. I don't know if that makes a difference tho, if it does not then ignore this comment.

2023-08-08 19:13 UTC, Naapperas commented on resources/views/errors/minimal.blade.php
> +            /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}a{background-color:transparent}code{font-fami
Where did you take this from?

2023-08-08 19:34 UTC, toni-santos commented on resources/views/errors/minimal.blade.php
> +            /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}a{background-color:transparent}code{font-fami
That was generated by laravel using `php artisan vendor:publish ` and the `laravel-errors` option.

2023-08-08 19:38 UTC, toni-santos commented on app/Exceptions/Handler.php
> +        if (in_array($response->status(), [500, 404, 403])) {
This was directly taken from [Inertia's documentation](https://inertiajs.com/error-handling#production), furthermore, as you can see by the commented line, it has been altered to make testing in this branch easier (we need to evidently revert it when pushing to main).

2023-08-08 19:40 UTC, toni-santos commented on app/Exceptions/Handler.php
> +        }
Like before, [Inertia's documentation](https://inertiajs.com/error-handling#production) is the source. As far as making it in a more `Laravel`-ish way, I'm not sure, I can look into it once we have the remaining, more pressing issues tackled :)

2023-08-08 20:01 UTC, Naapperas commented on app/Exceptions/Handler.php
> +        if (in_array($response->status(), [500, 404, 403])) {
Understood, but then it's their fault for having their code like that. We can do better and Pull those values into named constants :)

This allows for easier updates in the future, should they be needed.

Regarding the commented line, we could have something like a "feature flag", like "doNotTestDevAsProd" which, when or'ed with the commented expression, could impose a programmatic toggle on that condition. Maybe I'm complicating things but then, when we are ready to deploy the website, it's just a matter of changing that same feature flag (which could be kept as an environment variable).

What do you think?

2023-08-08 20:03 UTC, Naapperas commented on app/Exceptions/Handler.php
> +        }
Ok, sounds good, leaving this conversation open so it's easier to track.

2023-08-08 20:04 UTC, Naapperas commented on resources/views/errors/minimal.blade.php
> +            /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}a{background-color:transparent}code{font-fami
Oh, ok. Kinda weird for them to have all those styles like that but then that is that. Maybe que should clean them up but I'll leave that completely up to you.

2023-08-08 22:04 UTC, toni-santos commented on app/Exceptions/Handler.php
> +        if (in_array($response->status(), [500, 404, 403])) {
From what I read regarding this code, it seems that it is already controlled by an environmental flag, that can be `production`, `local` or `testing`, we could simply add a state to this flag like `maintenance_test` that would overwrite the other ones in the if condition. I think that's similar to what you are proposing, no?

2023-08-08 22:05 UTC, toni-santos commented on resources/views/errors/minimal.blade.php
> +            /*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}a{background-color:transparent}code{font-fami
I think that's a concern to another issue/PR since it concerns error pages rather than the maintenance page. Regardless, we are not using any of these templates since we are using Inertia for maintenance/errors.

2023-08-08 23:09 UTC, Naapperas commented on app/Exceptions/Handler.php
> +        if (in_array($response->status(), [500, 404, 403])) {
It is yes. It akl books down to a matter of taste and consistency.

2023-08-10 17:03 UTC, toni-santos commented on app/Exceptions/Handler.php
> +        if (in_array($response->status(), [500, 404, 403])) {
In order to make this easier, and to avoid accidentally making the site go into maintenance mode I suggest adding `maintenance` to the environments. The program flow would go as follows:
```php
        $DEVELOPMENT = ['maintenance', 'local', 'testing'];
        $ERROR_PAGES = [500, 404, 403];
        
        if (!app()->environment($DEVELOPMENT) && in_array($response->status(), $ERROR_PAGES)) {
            return Inertia::render('Error', ['status' => $response->status()])
                ->toResponse($request)
                ->setStatusCode($response->status());
        } elseif ($response->status() === 503 && app()->environment(['maintenance'])) {
            return Inertia::render('Maintenance')
                ->toResponse($request)
                ->setStatusCode($response->status());
        } elseif ($response->status() === 419) {
            return back()->with([
                'message' => 'The page expired, please try again.',
            ]);
        }
```

What do you think of this solution?

2023-08-10 17:06 UTC, toni-santos commented on app/Exceptions/Handler.php
> +        if (in_array($response->status(), [500, 404, 403])) {
I forgot to mention but to even make Laravel go into maintenance mode, `php artisan down` must be ran (and ` php artisan up` in order to get it back up). This solution also allows us to have a custom 503 page for regular unavailability errors.

2023-08-20 12:37 UTC, toni-santos commented
This is ready for a thorough review and merge.

2023-08-20 13:17 UTC, pedrosilva17 approved these changes, later dismissed
🚀🚀

2023-08-24 18:28 UTC, pedronunes19 submitted a review, later dismissed

2023-08-27 13:19 UTC, Naapperas requested changes

2023-08-27 13:19 UTC, Naapperas commented on .env
> +APP_ENV=local # Use maintenance_test to test the maitenance page
You use `maintenance` in the code, change this accordingly

2023-08-27 13:19 UTC, Naapperas commented on resources/js/Pages/Error.vue
> +})
@toni-santos any thoughts on this?

2023-08-27 13:19 UTC, Naapperas commented on resources/js/Pages/Maintenance.vue
> +<script setup>
Do the paths on the images created here always work? Pure curiosity, this is something I really don't know.

2023-08-27 14:08 UTC, toni-santos commented on resources/js/Pages/Error.vue
> +})
I don't believe it would make a difference, regardless, I believe this is an issue to be tackled at another time, seeing as it relates solely to error pages.

2023-08-27 14:16 UTC, toni-santos commented on resources/js/Pages/Maintenance.vue
> +<script setup>
From my testing and my cursory investigation it seems they do, but now that you mention I see that the images have not been committed. I believe they should be present in the `public` folder, whereas I placed them inside `storage`, I'll take a look at it.

2023-08-27 14:40 UTC, Naapperas approved these changes

2023-08-28 15:18 UTC, pedronunes19 approved these changes

2023-08-28 17:50 UTC, merged