Setup CI stack
semanadeinformatica/website pull request #31
Opened 2023-08-19 17:58 UTC by ttoino

Adds and configures workflows to test the application and check the quality of the code.

Adds and sets up the following tools:

- Laravel Pint (for php formatting)
- Prettier (for javascript formatting)
- Eslint (for javascript linting)
- Typescript and vue-tsc (for javascript type checking)

2023-08-19 19:59 UTC, Naapperas requested changes
What is the purpose of the multiple tsconfig files? Other than that and the things I pointed out, it all seems good.

2023-08-19 19:59 UTC, Naapperas commented on .github/workflows/ci.yml
> +          php-version: '8.2'
This version should come from a matrix or an externally defined variável, in my opinion.

2023-08-19 19:59 UTC, Naapperas commented on .github/workflows/ci.yml
> +          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
Same thing here, if possible

2023-08-19 19:59 UTC, Naapperas commented on .github/workflows/ci.yml
> +    name: Check Typescript code style
Shouldn't this be "Format..."?

2023-08-19 20:31 UTC, ttoino commented
> What is the purpose of the multiple tsconfig files? Other than that and the things I pointed out, it all seems good.

The typescript config is based on the one in create-vue, there's a file for the app itself and another one just for config files

2023-08-20 17:39 UTC, Naapperas commented
I'm of the opinion that props should be defined in a separate type, I believe it males the code easier to read. What do you think @ttoino ?

2023-08-21 01:14 UTC, ttoino commented on .github/workflows/ci.yml
> +    name: Check Typescript code style
I don't think so, that step only checks if the current files follow the wanted style, it doesn't format them.

2023-08-21 01:15 UTC, ttoino commented on .github/workflows/ci.yml
> +          php-version: '8.2'
You're right, I'll look into it

2023-08-21 01:17 UTC, ttoino commented
> I'm of the opinion that props should be defined in a separate type, I believe it males the code easier to read. What do you think @ttoino ?

I think you're right, the current iteration of the typescript code leaves a lot to be desired and needs to be improved, especially on the prop typing.

Also, for some reason vue-tsc is not working right now as there are a lot of typing errors in vscode but the CI step is green 🤨

2023-08-22 14:13 UTC, Naapperas commented on .github/workflows/ci.yml
> +    name: Check Typescript code style
I believe it previously used 'npm run format', this way ir.makes more sense

2023-08-29 12:53 UTC, pedrosilva17 submitted a review, later dismissed
Looks good to me. The tools chosen are adequate and the scripts will make our lives a lot easier when type checking and trying to maintain a consistent code format. Don't see anything wrong with the workflows either. Great job!

2023-08-29 15:07 UTC, toni-santos commented
LGTM, just missing the checks and should be good to merge! :+1:

2023-08-29 16:14 UTC, pedrosilva17 approved these changes
Same as before. LGTM 🐱‍👤

2023-08-29 16:19 UTC, toni-santos approved these changes

2023-09-01 19:56 UTC, Naapperas approved these changes

2023-09-01 19:58 UTC, merged