Started adding logs to application
semanadeinformatica/website pull request #315
Opened 2023-10-27 11:04 UTC by Naapperas

2023-10-29 18:17 UTC, ttoino requested changes

2023-10-29 18:17 UTC, ttoino commented on app/Actions/Fortify/CreateNewUser.php
> +        Log::info('Creating user with input: {input}', ['input' => Json::encode($data, true)]);
I don't think logging a user's password is a great idea 🥴

2023-10-29 18:17 UTC, ttoino commented on app/Http/Controllers/EventController.php
> +            return redirect()->back()->dangerBanner('Tens que ter sessão iniciada para fazer esta ação');
I don't like this error message, it sounds too robotic

2023-10-29 18:17 UTC, ttoino commented on app/Http/Controllers/QuestController.php
> +            return redirect()->back()->dangerBanner('Tens que estar autenticado para efetuar esta ação');
Same as above

2023-10-29 18:18 UTC, ttoino commented
Actually, now that I think about it, are those error messages when the user is not logged in even required? The routs have the fortify middleware anyway

2023-10-29 18:28 UTC, Naapperas commented on app/Actions/Fortify/CreateNewUser.php
> +        Log::info('Creating user with input: {input}', ['input' => Json::encode($data, true)]);
:sob: my bad

2023-10-29 18:28 UTC, Naapperas commented on app/Http/Controllers/EventController.php
> +            return redirect()->back()->dangerBanner('Tens que ter sessão iniciada para fazer esta ação');
:robot:

2023-10-29 18:29 UTC, Naapperas commented on app/Http/Controllers/EventController.php
> +            return redirect()->back()->dangerBanner('Tens que ter sessão iniciada para fazer esta ação');
Do you have any suggestions? @toni-santos suggested `Inicia sessão para fazer esta ação` :musical_note:

2023-10-29 18:30 UTC, Naapperas commented on app/Http/Controllers/QuestController.php
> +            return redirect()->back()->dangerBanner('Tens que estar autenticado para efetuar esta ação');
:robot:

2023-10-29 19:08 UTC, Naapperas commented
> Actually, now that I think about it, are those error messages when the user is not logged in even required? The routs have the fortify middleware anyway

routs

2023-10-29 22:47 UTC, Naapperas commented
> Actually, now that I think about it, are those error messages when the user is not logged in even required? The routs have the fortify middleware anyway

Perhaps these specific routes will never fall in that branch but better be safe than sorry.

2023-10-29 23:52 UTC, CiscoPr approved these changes

2023-10-31 13:09 UTC, ttoino approved these changes

2023-10-31 13:10 UTC, merged