Feature/competition leaderboards
semanadeinformatica/website pull request #319
Opened 2023-10-29 23:20 UTC by Naapperas

2023-10-29 23:26 UTC, pedrosilva17 commented
Any screenshots? 🙏

2023-10-29 23:48 UTC, Naapperas commented
> Any screenshots? 🙏

![image](https://github.com/semanadeinformatica/website/assets/23704084/a6c76387-6c61-4107-86c1-e0e3b3d97ce5)

![image](https://github.com/semanadeinformatica/website/assets/23704084/3daee9e8-87f7-4e66-a09f-5fc034ea279e)

![image](https://github.com/semanadeinformatica/website/assets/23704084/93909b9e-d555-471e-a175-250847160e33)

I just found an issue with the podium not updating when we change the current competition, gotta check into that.

2023-10-29 23:50 UTC, pedrosilva17 commented
The frontend looks fine, no glaring issues with the code either (from what I've seen). Fix that issue and it should be good to go

2023-10-31 13:22 UTC, ttoino requested changes

2023-10-31 13:22 UTC, ttoino commented on app/Http/Controllers/CompetitionController.php
> +        $leaderboard = $competition->teams()->orderBy('points', 'desc')->take(3)->get();
Can't we do this on the client? It would save a db query

2023-10-31 13:22 UTC, ttoino commented on app/Http/Controllers/CompetitionTeamCRUDController.php
We should probably also add a way to associate team members

2023-10-31 13:22 UTC, ttoino commented on resources/js/Components/Podium.vue
> +        </div>
I think it's ok to not have this on mobile, as it looks a little weird, and all teams are present in the list below

2023-10-31 13:22 UTC, ttoino commented on resources/js/Pages/Competition.vue
> +                            {{ team.name }} - {{ team.points }}
I think we should also show the team image and the points should be below the name or justified to the right

2023-11-01 14:19 UTC, ttoino approved these changes

2023-11-01 18:59 UTC, merged