add footer
semanadeinformatica/website pull request #34
Opened 2023-08-21 17:24 UTC by pedronunes19

Closes #20 

The footer is created as a component following the mocks.  #25 should be merged for the icons.

![Screenshot from 2023-08-21 18-19-23](https://github.com/semanadeinformatica/website-2023/assets/75331417/4d855f72-65cb-4764-9330-e441dd6e8071)

2023-08-22 14:05 UTC, Naapperas submitted a review, later dismissed
LGTM

2023-08-26 02:16 UTC, ttoino requested changes

2023-08-26 02:16 UTC, ttoino commented on resources/js/Components/Footer.vue
> +                </a>
This repetition should be avoided with the use of components, or with a for loop

2023-08-26 02:16 UTC, ttoino commented on resources/js/Components/Footer.vue
> +                </div>
Why are two divs necessary here?

2023-08-26 02:16 UTC, ttoino commented on resources/js/Components/Footer.vue
> +            <div class="flex gap-2 flex-row items-center w-full justify-evenly max-[900px]:hidden">
We should probably use tailwind's built-in breakpoints, not custom ones

2023-08-26 16:33 UTC, pedronunes19 commented on resources/js/Components/Footer.vue
> +                </div>
I don't think they're strictly necessary, it was just a away of separating the styles (mostly the `grid`). Follows pretty much the same structure that was being used for the maintenance page.

2023-08-26 23:09 UTC, ttoino commented on resources/js/Components/Footer.vue
> +                </div>
While I don't really like it, it's an ok compromise as stuffing all classes in a single element would also be hard for readability

2023-08-26 23:10 UTC, ttoino approved these changes

2023-08-27 13:09 UTC, Naapperas approved these changes
LGTM! @pedronunes19 I left some suggestions that can be ignored if you believe they don't make much sense.

2023-08-27 13:09 UTC, Naapperas commented on resources/js/Components/Footer.vue
> +                    <a class="p-2.5 rounded-full flex w-fit" :class="platform[1]" target="_blank" :href="platform[2]">
The contacts could be objects, that would make the code a little cleaner. This is optional, so if you feel it does not make sense feel free to ignore this comment.

2023-08-27 13:09 UTC, Naapperas commented on resources/js/Components/Footer.vue
> +                    </template>
Can't we have this logic separated? That way it is not duplicated (unless I saw things wrong but I double checked and believe they are the same for the mobile and desktop styles)

2023-08-28 20:51 UTC, merged