Index Page
semanadeinformatica/website pull request #37
Opened 2023-08-29 16:31 UTC by toni-santos

Closes #33

2023-08-29 16:32 UTC, toni-santos commented
This is a WIP, most elements are not correctly aligned and are not yet mobile ready. Help and suggestions appreciated :)

2023-08-31 03:14 UTC, toni-santos commented
Desktop is mostly done, there is only a small issue that I've not been able to fix.
When scrolling through the speakers a small transition plays where a speaker's image increases in size whilst the current one becomes smaller, this makes the carousel height to change which makes the entire page's height shift. Any help regarding this issue is greatly appreciated!

2023-09-02 12:00 UTC, Naapperas commented
@toni-santos remember: se are already using Typescript, so we should.make.use of the type system. When defining props, teu to use a type as a genéric instead of an object.

2023-09-03 07:59 UTC, ttoino requested changes

2023-09-03 07:59 UTC, ttoino commented on resources/js/Components/Home/Map.vue
> +    '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors';
Adding type hints here is redundant, the inferred types should be correct

2023-09-03 07:59 UTC, ttoino commented on resources/js/Components/Home/SpeakerSlide.vue
> +);
I think this can be replaced with a `reactive` or `computed` call, but I'm not sure

2023-09-03 07:59 UTC, ttoino commented on resources/js/Pages/Home.vue
> +});
This should use typescript types, and `modelValue` should get a more descriptive type.

2023-09-03 07:59 UTC, ttoino commented on resources/js/app.ts
> +addIcons(...Fa);
Do we need two icon families? Also, font-awesome is an aggregator of icons, so not all of their icons will look good together.

2023-09-03 11:33 UTC, CiscoPr commented
I'm being quite nitpicky, but I believe in the footer, "niaefeup" should be capitalized as it represents the name of an organization, and it's predominantly presented this way on other platforms.
![Captura de ecrã 2023-09-03 112341](https://github.com/semanadeinformatica/website-2023/assets/79597450/4c56dfdc-d0cf-43d6-96b5-139664fd6db8)

2023-09-03 13:54 UTC, toni-santos commented on resources/js/Components/Home/SpeakerSlide.vue
> +);
Nice catch, didn't know `computed` could be so useful!

2023-09-03 13:56 UTC, toni-santos commented on resources/js/Pages/Home.vue
> +});
This was code left from the `Welcome.vue` file, which I used to make this one, that I forgot to remove.

2023-09-03 14:06 UTC, toni-santos commented on resources/js/app.ts
> +addIcons(...Fa);
font-awesome was added since some icons from io-icons do not behave correctly when setting their colors, as documented in [this issue](https://github.com/Renovamen/oh-vue-icons/issues/12) from a couple years ago.
Whilst it is possible to [add only specific icons](https://oh-vue-icons.js.org/docs), rather than the entire icon family, I believe it might be easier for other features where this issue arises to have the icon family available making it easier to use a more adequate icon.
Regardless, we must still be aware that io-icons is the main icon family, fa-icons acts only as a backup for these cases. Alternatively, we could ask the design team if switching the icon family is worth it.

2023-09-03 18:20 UTC, pedronunes19 commented
> I'm being quite nitpicky, but I believe in the footer, "niaefeup" should be capitalized as it represents the name of an organization, and it's predominantly presented this way on other platforms. ![Captura de ecrã 2023-09-03 112341](https://user-images.githubusercontent.com/79597450/265261214-4c56dfdc-d0cf-43d6-96b5-139664fd6db8.png)

That's my fault really (it's copied from the design team's mocks)

2023-09-03 18:22 UTC, pedronunes19 commented
![Screenshot from 2023-09-03 19-18-03](https://github.com/semanadeinformatica/website-2023/assets/75331417/fb97fb56-be4d-46d0-ab80-6d965371f820)

I believe you're aware of this @toni-santos but the alignment here seems a bit odd

2023-09-03 18:27 UTC, pedronunes19 requested changes

2023-09-03 18:27 UTC, pedronunes19 commented on resources/js/Pages/Home.vue
> +                    novembro. Os participantes têm a seu dispor palestras e
We should probably change this, despite some other text (number of talks/workshops/etc.) needing a revision later

2023-09-03 18:52 UTC, Naapperas commented
@toni-santos I just thought of this: we should have the beginning and end dates not be hardcoded in the markup. They could be defined externally or added as attributes to an edition (in the last case, the website could just always use the latest edition available, regardless of whether it is active or not, food for thought)

2023-09-03 18:55 UTC, Naapperas commented
This is not scoped to this PR but I'll leave it here due to context; the dates part could/should still be handled here IMO.

Basically, if we had more attributes to an edition, we could define the site's theme as a JSON attribute (SQL standard has those now and PgSQL supports then already if I'm not mistaken) of the editon, as well as any other important data that might be needed.

2023-09-03 19:45 UTC, toni-santos commented
> ![Screenshot from 2023-09-03 19-18-03](https://user-images.githubusercontent.com/75331417/265281925-fb97fb56-be4d-46d0-ab80-6d965371f820.png)
> 
> I believe you're aware of this @toni-santos but the alignment here seems a bit odd

![image](https://github.com/semanadeinformatica/website-2023/assets/72560332/c8e0b18c-45fb-44c7-91fd-0564575c0d03)

I'm not able to get a better screenshot, but I've changed the code so that the position of the titles, where applicable, are not computed by me but instead by CSS centering mechanisms which I then just add a margin in order to take into account the shadow when centering.

2023-09-03 19:47 UTC, toni-santos commented on resources/js/Pages/Home.vue
> +                    novembro. Os participantes têm a seu dispor palestras e
This text must be revised once we are closer to the event, seeing as its information, alongside the ones from the "call to action" are more promotional/flavor rather than technical.

2023-09-03 19:53 UTC, toni-santos commented
> @toni-santos I just thought of this: we should have the beginning and end dates not be hardcoded in the markup. They could be defined externally or added as attributes to an edition (in the last case, the website could just always use the latest edition available, regardless of whether it is active or not, food for thought)

That's a great idea, in fact all pages should just be receiving information from the database and then displaying them through the mechanisms and interfaces that are respective to each edition. For this PR however, my idea was to keep it frontend only, seeing as the information being displayed here comes from sources from the database that are yet to be implemented in the backend, mainly, the speakers.

> This is not scoped to this PR but I'll leave it here due to context; the dates part could/should still be handled here IMO.
> 
> Basically, if we had more attributes to an edition, we could define the site's theme as a JSON attribute (SQL standard has those now and PgSQL supports then already if I'm not mistaken) of the editon, as well as any other important data that might be needed.

Agreed, and related to what I said regarding the first point :)

2023-09-03 20:05 UTC, toni-santos commented
I have fixed the issue I reported at the beginning where the carousel's changing height would make the rest of the page grow and shrink in size, however due to the fact that it made it impossible to achieve a clean transition I have disabled the animation/transition on the change of size of the image, furthermore it made the carousel look really weird when switching images. We could revisit this if we deem that the size transition is relevant and enhances the page, however due to its appearance I'd suggest against it.

Following this I believe there aren't anymore tweaks or fixes left. Please test the page out, mainly the speaker's carousel and its behavior when resizing and interacting with the page in responsive ways.

2023-09-03 20:16 UTC, toni-santos commented on resources/js/Components/Home/SpeakersCarousel.vue
> +    await new Promise((r) => setTimeout(r, 500)).then(wrapperHeight);
Forgot to mention, but from what I've been able to search and find regarding executing code on page load with Vue3, it seems that currently the `window.onload` [event is broken](https://github.com/vuejs/core/issues/5844), as `onMount` is being executed after the load/(not at all?) which means that we aren't able to wait for the full page load to get the correct height in `wrapperHeight`. As such this was the only way I found of running the function for the first time on page load, it is obviously less than ideal and any help is greatly appreciated.

2023-09-04 13:34 UTC, pedronunes19 approved these changes, later dismissed

2023-09-04 21:26 UTC, Naapperas commented on resources/js/Components/Home/SpeakersCarousel.vue
> +    await new Promise((r) => setTimeout(r, 500)).then(wrapperHeight);
I think you can set the timeout value to 0 and its still Will have the desired behavior: still better than waiting for some time

2023-09-04 21:26 UTC, Naapperas commented on resources/js/Components/Home/SpeakersCarousel.vue
> +    await new Promise((r) => setTimeout(r, 500)).then(wrapperHeight);
@ttoino thoughts?

2023-09-07 02:08 UTC, toni-santos commented
I may have not noticed or it may have been recently added, but there were some modals missing that provide some more information about the sponsors, this is now implemented with [this package](https://vue-final-modal.org/). It seems to be lightweight and easy to use, a good option whenever we need to use any modals!

2023-09-07 02:09 UTC, toni-santos commented on resources/js/Components/Home/SpeakersCarousel.vue
> +    await new Promise((r) => setTimeout(r, 500)).then(wrapperHeight);
I have attempted to use 0 as suggested but was unable to have the same behavior as with 500. I am befuddled by this problem...

2023-09-07 12:45 UTC, Naapperas commented
Inertia apparently has modal components

2023-09-12 13:43 UTC, pedronunes19 submitted a review, later dismissed

2023-09-12 15:17 UTC, CiscoPr submitted a review, later dismissed

2023-09-12 16:39 UTC, Naapperas requested changes
I saw a lot of `px` units and I'm kinda of scared: are they really necessary?

Other than that, I'm going to assume that you are waiting for #36 for the navbar: currently the "about us" section is half-cut and it could look better.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/Map.vue
> +        </l-map>
This is a matter of opinion but I would prefer if you use the components' name  in camel case instead. Makes it clearer that they are custom components.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/Map.vue
> +        </l-map>
Also, the maps looks a bit small in my opinion, I don't know if it would also look good if it were bigger.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/SpeakerSlide.vue
> +        />
The transition between images should be smoother, right now the "next" picture just pops up instantly.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/SpeakerSlide.vue
> +        </p>
Not sure if the name should be disabled or simply smaller if the "speaker" slide is not active. Give it a try.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Footer.vue
> +            <p>Copyright &copy; 2023 NIAEFEUP, todos os direitos reservados</p>
We could have a link in `NIAEFEUP` to our website.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/SpeakerSlide.vue
> +});
This seems a bit off, slides should not need to be aware of the currently active slide. Perhaps they should just care if they are active or not and its up to their parent element to calculate that.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/SpeakersCarousel.vue
> +        "li.carousel__slide--active:nth-child(11) > div:nth-child(1)",
Not too keen on us depending on this: we have no guarantees that we will only have 10 speakers. This should come from a "through" relationship between speakers and editions, and there should be some fallback UI in case there are no speakers (as is the case now).

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/SpeakersCarousel.vue
> +        <Slide v-for="slide in 10" :key="slide">
Same as above.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/SpeakersCarousel.vue
> +            <SpeakerSlide :slideID="slide" :currentSlide="activeSpeaker" />
Regarding a comment made above, we should calculate here if this slide should be active or not.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/Sponsor.vue
> +const options = ref(getInitialValues());
Is there some reason for this code to be like this? Why not just set the ref directly?

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/Sponsor.vue
> +        <ModalsContainer />
According to the [documentation](https://vue-final-modal.org/get-started/guide/setup#add-modalscontainer-to-vue-tree), you only need to add this component once, in a place that is common to every page that might make use of modals.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/Sponsor.vue
> +}
Should we mess with VFM directly like this?

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Components/Home/SponsorBanner.vue
I don't really like the way this was done here. I feel there's a lot of unnecessary repetition. We should simply have a component to render a group of sponsors, with these being passed in as props (this still needs to be thought about better). Other stuff such as color could also be passed in as props.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Layouts/AppLayout.vue
> -            </main>
Why did you remove the `main` element from here? Why did you move it elsewhere?

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Pages/Home.vue
> +        <main class="bg-2023-bg">
Same as above.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Pages/Home.vue
> +                        >2023</span
This should come from the latest edition available, imo.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Pages/Home.vue
> +                    25 a 31 de outubro
Same as above. We do not have that implemented yet, I think, but is something to keep in mind.

2023-09-12 16:39 UTC, Naapperas commented on resources/js/Pages/Home.vue
> +                <SponsorBanner tier="silver"></SponsorBanner>
This relates to the comment made above: the tiered sponsors should be injected into this View on page load: it is not the Banners responsibility to differentiate between them.

2023-09-12 16:39 UTC, Naapperas commented on routes/web.php
> +    return Inertia::render('Home', [
These props should be changed.

We should have information about:
- The edition
  - Its sponsors
  - Its speakers
  - Relevant dates

2023-09-12 16:40 UTC, Naapperas commented on resources/js/Components/Home/SpeakersCarousel.vue
> +        "li.carousel__slide--active:nth-child(11) > div:nth-child(1)",
This is to say: this query looks kinda weird to me.

2023-09-12 16:49 UTC, toni-santos commented on resources/js/Components/Home/Map.vue
> +        </l-map>
I have kept these component's names according to their [documentation](https://github.com/vue-leaflet/vue-leaflet).

Increasing map size isn't problematic, seeing as the map is by default responsive and should not break anything else.

2023-09-12 16:50 UTC, toni-santos commented on resources/js/Components/Home/SpeakerSlide.vue
> +        />
I have discussed this issue [here](https://github.com/semanadeinformatica/website-2023/pull/37#issuecomment-1704390029).

2023-09-12 16:52 UTC, toni-santos commented on resources/js/Components/Home/SpeakerSlide.vue
> +        </p>
According to the Figma designs it should only appear when it is active. I could try this however, maybe we should talk with the design team regarding it.

2023-09-12 17:02 UTC, Naapperas commented on resources/js/Components/Home/Map.vue
> +        </l-map>
See if you can use different names

2023-09-12 17:03 UTC, toni-santos commented on resources/js/Components/Home/SpeakerSlide.vue
> +});
This setup comes from the fact that there is no way to watch for the current active slide in the [carousel package we are using](https://ismail9k.github.io/vue3-carousel/getting-started.html). Therefore my solution was to make each `SpeakerSlide` know its ID and use `handleSlideStart` to update the current slide's value inside `SpeakerSlide`, changing the value of `active` that way.

2023-09-12 17:07 UTC, toni-santos commented on resources/js/Components/Home/SpeakersCarousel.vue
> +        "li.carousel__slide--active:nth-child(11) > div:nth-child(1)",
I agree, I used the browser's CSS selector function for this, there is a better query.

2023-09-12 17:08 UTC, Naapperas commented on resources/js/Components/Home/SpeakerSlide.vue
> +        </p>
I've spoken with @madalenaye and she says we should add the names.

2023-09-12 17:13 UTC, toni-santos commented on resources/js/Components/Home/Sponsor.vue
> +const options = ref(getInitialValues());
[This](https://vue-final-modal.org/use-cases/playground) was used as a basis. I'm not sure if it can be omitted.

2023-09-12 17:20 UTC, toni-santos commented on resources/js/Components/Home/Sponsor.vue
> +}
VFM refers to Vue Final Modal, this is the [supposed usage](https://vue-final-modal.org/get-started/guide/setup#plain-css).

2023-09-12 17:21 UTC, Naapperas commented on resources/js/Components/Home/Sponsor.vue
> +const options = ref(getInitialValues());
It can because, contrary to that example where they reuse the function, you only call it here. In fact, I can't even see the reason to use a ref here since you do not update its value, or at least nowhere that I could see.

2023-09-12 17:54 UTC, Naapperas commented on resources/js/Components/Home/SpeakerSlide.vue
> +});
I understand that, but each slide just needs to know if it is active or not, not that it is slide X and currently slide Y is the active one. That calculation should come from the parent component.

2023-09-13 22:41 UTC, toni-santos commented
Branch has been rebased and is ready for review :) Please check it out!

2023-09-13 23:28 UTC, Naapperas approved these changes, later dismissed

2023-09-13 23:33 UTC, Naapperas commented on routes/web.php
> +    return Inertia::render('Home', [
To be done in another PR.

2023-09-13 23:33 UTC, Naapperas commented on resources/js/Pages/Home.vue
> +                    25 a 31 de outubro
To be done in another PR.

2023-09-13 23:33 UTC, Naapperas commented on resources/js/Pages/Home.vue
> +                        >2023</span
To be done in another PR.

2023-09-13 23:33 UTC, Naapperas commented on resources/js/Components/Home/SpeakerSlide.vue
> +        />
To be done in another PR.

2023-09-13 23:34 UTC, Naapperas commented
Don't forget to rebase this branch

2023-09-14 10:39 UTC, ttoino approved these changes, later dismissed
LGTM, I just have two very slight nitpicks:

At small screen sizes, maybe this title should be centered, and the grid reduced to one column.
![image](https://github.com/semanadeinformatica/website-2023/assets/14280476/bd20ef60-7a7f-4518-ab19-d5a7e0270a84)

Also at very small screen sizes, the speakers should either be smaller or the main speaker should have a higher z-index to appear on top.
![image](https://github.com/semanadeinformatica/website-2023/assets/14280476/f08d59d7-70b3-4dc5-b069-938f643493f8)

2023-09-14 13:00 UTC, Naapperas approved these changes

2023-09-14 14:08 UTC, ttoino approved these changes

2023-09-14 14:49 UTC, merged