Add admin features (CRUD)
semanadeinformatica/website pull request #38
Opened 2023-08-30 13:12 UTC by ttoino

Closes #30.

2023-09-12 03:21 UTC, Naapperas commented
Is there anything missing in this PR @ttoino?

2023-09-13 11:06 UTC, ttoino commented
> Is there anything missing in this PR @ttoino?

I think it's done.

2023-09-13 11:25 UTC, Naapperas submitted a review, later dismissed
LGTM. I believe that the pages should live under an `admin` folder and not a `CRUD` folder but that is not really that important right now.

2023-09-13 11:25 UTC, Naapperas commented on resources/js/Components/CRUD/Row.vue
> +    item: Model;
Why didn't you use a generic here like you did in the Table component?

2023-09-13 11:25 UTC, Naapperas commented on resources/js/Components/CRUD/Row.vue
> +    item: Model;
Also, another nitpick: in other places you create an interface called Props but here you are defining the type inline, not really important but it's a matter of consistency.

2023-09-13 13:12 UTC, Naapperas commented
The tests are failing with the given message:
`Class "Illuminate\Support\Facades\App\Models\Student" not found`

Perhaps we messed up some paths, I believe this is not a problem with the logic itself of the website.

2023-09-13 16:32 UTC, ttoino commented
> The tests are failing with the given message: `Class "Illuminate\Support\Facades\App\Models\Student" not found`
> 
> Perhaps we messed up some paths, I believe this is not a problem with the logic itself of the website.

It was a problem with the factories, I added the usertype to the $with property, but the id was 0, causing an exception. It's now fixed.

2023-09-13 16:52 UTC, ttoino commented on resources/js/Components/CRUD/Row.vue
> +    item: Model;
I didn't use a generic because that particular element does not need any properties outside the `Model` interface and it doesn't expose that prop anywhere else so being a generic wouldn't be advantageous.

2023-09-13 20:07 UTC, Naapperas requested changes
LGTM :rocket:

2023-09-13 20:07 UTC, Naapperas commented on app/Http/Controllers/CRUDController.php
Maybe we could add a `getById` method to CRUD Controllers? I can see it being useful.

2023-09-13 20:07 UTC, Naapperas commented on app/Http/Controllers/CRUDController.php
Besides that, you should write some documentation to explain what each thing does., for future reference.

2023-09-13 20:07 UTC, Naapperas commented on app/Http/Controllers/CRUDController.php
> +    }
Shouldn't we also have a `destroyed` method?

2023-09-13 22:20 UTC, ttoino commented on app/Http/Controllers/CRUDController.php
> Maybe we could add a `getById` method to CRUD Controllers? I can see it being useful.

Sure, that'll be useful in the future if we need more in depth info for some models, like for validating quest requirements or forcing a user to renew their password.

> Besides that, you should write some documentation to explain what each thing does., for future reference.

Makes sense.

2023-09-13 22:21 UTC, ttoino commented on app/Http/Controllers/CRUDController.php
> +    }
I can't see how that would be useful, but I'll add it for completeness.

2023-09-13 22:24 UTC, Naapperas commented on app/Http/Controllers/CRUDController.php
> +    }
It might not be needed at all, its just a matter of completeness as you said

2023-09-13 22:25 UTC, Naapperas approved these changes, later dismissed

2023-09-13 22:31 UTC, Naapperas approved these changes

2023-09-13 22:42 UTC, toni-santos approved these changes

2023-09-13 22:43 UTC, merged