Sticker component for sticker book
semanadeinformatica/website pull request #44
Opened 2023-09-05 21:18 UTC by toni-santos

Closes #40.

2023-09-05 23:54 UTC, ttoino requested changes
By @Naapperas

2023-09-05 23:54 UTC, ttoino commented on resources/js/Components/Sticker.vue
> +    <div class="group relative sticker-clip-path w-[220px] h-[220px] flex justify-center basis-0 overflow-hidden" :class="`bg-${color}` || {[`grayscale`] : !active}" >
Even though `color` can be the empty string (and thus have a falsy value), the expression `bg-{color}` will always have a truthy value, making it the only value to ever be used.

One way of doing this could be like the following:

```suggestion
    <div class="group relative sticker-clip-path w-[220px] h-[220px] flex justify-center basis-0 overflow-hidden" :class="active ? `bg-${color}` || 'grayscale'" >
```

The syntax might not be right but you get the point. If I'm mistaken please correct me.

2023-09-05 23:54 UTC, ttoino commented on resources/js/Components/Sticker.vue
> +    <div class="group relative sticker-clip-path w-[220px] h-[220px] flex justify-center basis-0 overflow-hidden" :class="`bg-${color}` || {[`grayscale`] : !active}" >
As a bonus, we could look into the [clsx](https://www.npmjs.com/package/clsx) package on NPM to handle this kinds of things for us.

2023-09-05 23:54 UTC, ttoino commented on resources/js/Components/Sticker.vue
> +    <div class="group relative sticker-clip-path w-[220px] h-[220px] flex justify-center basis-0 overflow-hidden" :class="`bg-${color}` || {[`grayscale`] : !active}" >
Also, won't we run into problems for having the `class` attribute repeated? I genuinely don't know.

2023-09-06 13:58 UTC, toni-santos commented on resources/js/Components/Sticker.vue
> +    <div class="group relative sticker-clip-path w-[220px] h-[220px] flex justify-center basis-0 overflow-hidden" :class="`bg-${color}` || {[`grayscale`] : !active}" >
I don't think that syntax would work, the goal is not to have an if statement where we check `active` and either apply the class `grayscale` or `bg-${color}`, but rather have the bind apply `bg-${color}` everytime and `grayscale` only when `!active` is true. I'm not sure if this is the behavior the design team intended but for a first draft should be good enough at showing if a sticker has been awarded or not.
Regarding the repeated `class` attribute, this is an intended use of Vue's [class/style bindings](https://vuejs.org/guide/essentials/class-and-style.html#binding-html-classes).

2023-09-06 14:26 UTC, Naapperas commented on resources/js/Components/Sticker.vue
> +    <div class="group relative sticker-clip-path w-[220px] h-[220px] flex justify-center basis-0 overflow-hidden" :class="`bg-${color}` || {[`grayscale`] : !active}" >
The link you provided mentions binding `class` to Arrays, take a look at those examples since I believe that is what you wanted to achieve.

2023-09-06 16:08 UTC, ttoino commented on resources/js/Components/Sticker.vue
> +    </svg>
This svg should only be rendered once, this can be achieved with the Head component as is highlighted in the Inertia docs: https://inertiajs.com/title-and-meta#multiple-head-instances

2023-09-07 02:49 UTC, toni-santos commented on resources/js/Components/Sticker.vue
> +    </svg>
This did not seem to work, not only was the svg still being added multiple times, only this time in the head.
![image psd](https://github.com/semanadeinformatica/website-2023/assets/72560332/821c753a-fcca-4474-9fed-c0a59767b168)

2023-09-07 12:38 UTC, ttoino commented on resources/js/Components/Sticker.vue
> +    </svg>
Did you add the head-key attribute?

2023-09-07 14:25 UTC, toni-santos commented on resources/js/Components/Sticker.vue
> +    </svg>
In the screenshot I didn't but I tried and it did only create a single svg, however I wasn't able to select the clipPath. A simple fix, and given that this component will only be used on a single page, we can include the svg in its parent container and all stickers will be able to use that svg. What do you think about this?

2023-09-16 23:52 UTC, Naapperas approved these changes, later dismissed

2023-09-17 00:22 UTC, Naapperas approved these changes

2023-09-17 00:23 UTC, ttoino approved these changes

2023-09-17 00:34 UTC, merged