Creation of the competition page
semanadeinformatica/website pull request #47
Opened 2023-09-09 17:39 UTC by CiscoPr

2023-09-13 13:09 UTC, Naapperas requested changes

2023-09-13 13:09 UTC, Naapperas commented on resources/js/Pages/Competition.vue
> +    <Podium></Podium>
The podium component should be inside the AppLayout element.

2023-09-13 20:10 UTC, Naapperas requested changes

2023-09-13 20:10 UTC, Naapperas commented on resources/js/Pages/Competition.vue
> +});
These props are the default ones for Jetstream, please change or remove them.

2023-09-16 16:41 UTC, CiscoPr commented
For now, this is the appearance of the full competition page
![Screenshot 2023-09-16 at 17-40-26 Competition - SINF Website 2023](https://github.com/semanadeinformatica/website-2023/assets/79597450/8891afde-1bb5-4e3e-add2-088ea0087a0c)

2023-09-16 17:10 UTC, toni-santos reviewed
Great progress, just some minor tweaks left :)

2023-09-16 17:10 UTC, toni-santos commented on public/images/default_icon.png
This looks a bit pixelated when the podium is at its largest, maybe using an `svg` or something of the sort could help. Furthermore, whilst I personally like this style, it is jarring when in the context of the rest of the website, we might need to discuss this issue better with the design team as to figure out a good image.

2023-09-16 17:10 UTC, toni-santos commented on resources/js/Pages/Competition.vue
> +        <Podium></Podium>
The podium looks really big on my screen, is this intended? Regardless, I don''t think making it a little smaller would hurt the overall presentation.

2023-09-16 17:10 UTC, toni-santos commented on resources/js/Pages/Competition.vue
> +                class="absolute top-[15px] m-4 flex justify-center p-3 text-4xl font-black text-2023-red"
Why is this absolutely positioned?

2023-09-16 17:10 UTC, toni-santos commented on resources/js/Pages/Competition.vue
> +            </h2>
This is really big, especially on smaller screens, maybe adding a breakpoint and reducing the size could help.

2023-09-16 17:10 UTC, toni-santos commented on public/images/default_icon.png
Also, regardless of the prior, I think it would look cool if this had a blur effect :)

2023-09-16 19:32 UTC, pedronunes19 commented
![image](https://github.com/semanadeinformatica/website-2023/assets/75331417/5b893176-7b35-4dd6-89b2-f52edbe4b4d1)

This effect is missing from the participation button (example from login form). Other than that I agree with toni's observations.

2023-09-17 01:47 UTC, ttoino requested changes
Looks really good, but I agree with @toni-santos, the podium looks too big on large screens, maybe add a max-width

2023-09-17 01:47 UTC, ttoino commented on resources/js/Pages/Competition.vue
> +            >
Don't force a specific size for this button (especially not one using pixels). Also, this should be a Link, as this will link to another page.

2023-09-17 01:47 UTC, ttoino commented on resources/js/Pages/Competition.vue
> +                class="absolute top-[15px] m-4 flex justify-center p-3 text-4xl font-black text-2023-red"
Also, don't use pixels for its position

2023-09-17 11:09 UTC, CiscoPr commented on public/images/default_icon.png
Hmmm, yeah i see, i will try and add that effect then

2023-09-17 11:12 UTC, CiscoPr commented on resources/js/Pages/Competition.vue
> +                class="absolute top-[15px] m-4 flex justify-center p-3 text-4xl font-black text-2023-red"
> Why is this absolutely positioned?
here i used absolute because it was the only solution i saw at the time to display the ```h1``` correctly

2023-09-17 11:13 UTC, CiscoPr commented
> ![image](https://user-images.githubusercontent.com/75331417/268467810-5b893176-7b35-4dd6-89b2-f52edbe4b4d1.png)
> 
> This effect is missing from the participation button (example from login form). Other than that I agree with toni's observations.

Oh i totally forgot about that, thanks

2023-09-17 11:14 UTC, CiscoPr commented on resources/js/Pages/Competition.vue
> +            >
Ok, got it. Also, do we already know to what page the link will redirect to?

2023-09-17 13:37 UTC, ttoino commented on resources/js/Pages/Competition.vue
> +            >
I don't think so, but ideally it would come from the database

2023-09-17 15:33 UTC, toni-santos requested changes
I believe you missed the change in the `Regulamento` font size. Other than that and the comment I left it's pretty much done.

2023-09-17 15:33 UTC, toni-santos commented on resources/js/Components/Podium.vue
> +                class="bg-opacity-0 hover:blur ease-in-out duration-300"
I'm not sure if the blur effect should be on hover or permanent.

2023-09-17 15:35 UTC, CiscoPr commented
Regarless of the other corrections currently missing, the blur effect on the podium mentioned by @toni-santos is presented below. I couldn't show it correctly on the recording but the image gets blurred when the mouse hovers over it. Please give any feedback regarding it :)

[Screencast from 17-09-2023 16:30:36.webm](https://github.com/semanadeinformatica/website-2023/assets/79597450/94a0dddd-e99d-484a-89ef-3db8286cc128)

2023-09-17 15:38 UTC, CiscoPr commented
> I believe you missed the change in the `Regulamento` font size. Other than that and the comment I left it's pretty much done.

Yeah, mb, i forgot about it, thx for pointing it out

2023-09-17 15:40 UTC, CiscoPr commented on resources/js/Components/Podium.vue
> +                class="bg-opacity-0 hover:blur ease-in-out duration-300"
imo it makes more sense applying it on hover? Since these images will be of the prizes themselves, i think it makes more sense for the user to see the images normally

2023-09-17 17:14 UTC, diogofonte commented
> Regarless of the other corrections currently missing, the blur effect on the podium mentioned by @toni-santos is presented below. I couldn't show it correctly on the recording but the image gets blurred when the mouse hovers over it. Please give any feedback regarding it :)
> Screencast.from.17-09-2023.16.30.36.webm

The effect looks good, but I think that the blur effect should be in the other two positions. For example, if I hover the 1st, the 2nd and the 3rd images get blurred, to highlight the 1st one.
I don´t know if this is the idea of the design team, but it is just a suggestion

2023-09-17 20:32 UTC, ttoino requested changes

2023-09-17 20:32 UTC, ttoino commented on resources/js/Pages/Competition.vue
> +                class="relative mt-5 h-[3rem] w-[10rem] content-center justify-center border border-black bg-2023-teal-dark text-center text-2xl font-semibold text-white shadow-2023-orange transition
This is better, but I'd still feel better if you used padding to change the size of the button.

2023-09-17 21:20 UTC, Naapperas commented
@CiscoPr don't forget to mark outdated conversations as resolved.

2023-09-17 21:21 UTC, Naapperas commented
And to rebase this branch with the main branch.

2023-09-18 16:39 UTC, CiscoPr commented on resources/js/Components/Podium.vue
> +                class="bg-opacity-0 hover:blur ease-in-out duration-300"
currently i'm just waiting on the opinion of the image department. However, i already talked to one of the members and they approved the way it is. Either way, i'm gonna wait for the final opinion on this matter

2023-09-19 01:02 UTC, ttoino approved these changes, later dismissed

2023-09-19 07:38 UTC, toni-santos submitted a review, later dismissed

2023-09-19 09:47 UTC, Naapperas requested changes

2023-09-19 09:47 UTC, Naapperas commented on resources/js/Pages/Competition.vue
> +                class="relative mt-5 content-center justify-center border border-black bg-2023-teal-dark px-8 py-2 text-center text-2xl font-semibold text-white shadow-2023-orange transition-shadow h
```suggestion
                class="relative mt-5 content-center justify-center border border-black bg-2023-teal px-8 py-2 text-center text-2xl font-semibold text-white shadow-2023-orange transition-shadow hover:shadow-md active:shadow-none"
```
I believe this button is currently too dark in my opinion

2023-09-19 09:47 UTC, Naapperas commented on resources/js/Components/Podium.vue
> +                class="bg-opacity-0 duration-75 ease-out hover:blur-sm"
```suggestion
                class="bg-opacity-0 duration-75 ease-out blur-md hover:blur-none"
```

2023-09-19 09:47 UTC, Naapperas commented on resources/js/Components/Podium.vue
> +                class="bg-opacity-0 duration-75 ease-out hover:blur-sm"
```suggestion
                class="bg-opacity-0 duration-75 ease-out blur-md hover:blur-none"
```

2023-09-19 09:47 UTC, Naapperas commented on resources/js/Components/Podium.vue
> +                class="bg-opacity-0 duration-75 ease-out hover:blur-sm"
```suggestion
                class="bg-opacity-0 duration-75 ease-out blur-md hover:blur-none"
```

2023-09-19 09:52 UTC, Naapperas commented
Other than this, I noticed that when the mouse hovers over the ribbons the blur effect resets to its default on the element. [There](https://cssf1.com/snippet/access-child-elements-in-tailwindcss) [are](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiUqdiNs7aBAxVFaqQEHXf7DQ8QFnoECBcQAQ&url=https%3A%2F%2Fwww.geeksforgeeks.org%2Fhow-to-access-all-direct-children-of-a-div-in-tailwind-css%2F&usg=AOvVaw1W17Z4sCnx2_xw9l6GtMz8&opi=89978449) [ways](https://stackoverflow.com/questions/67119992/how-to-access-all-the-direct-children-of-a-div-in-tailwindcss) to do this based on the parent, please use what you thinks is best for this case.

2023-09-19 11:14 UTC, Naapperas approved these changes

2023-09-19 11:21 UTC, toni-santos approved these changes

2023-09-19 11:32 UTC, merged