Student Profile Page
semanadeinformatica/website pull request #48
Opened 2023-09-10 18:32 UTC by pedronunes19

Closes #29

2023-09-10 18:36 UTC, pedronunes19 commented
Very early draft. Student info (name, socials, profile picture, CV) still needs to be properly displayed on this page. Student's will be able to upload files and edit personal info (modal).

2023-09-17 19:15 UTC, pedronunes19 commented
The profile picture request is returning a 404, although the picture is correctly stored locally.

2023-09-17 20:09 UTC, Naapperas commented
> The profile picture request is returning a 404, although the picture is correctly stored locally.

Have you run `php artisan storage:link`?

2023-09-17 20:33 UTC, ttoino commented
> > The profile picture request is returning a 404, although the picture is correctly stored locally.
> 
> Have you run `php artisan storage:link`?

Additionally, the `APP_URL` env variable is wrong on `main`, but it's fixed in #69.

2023-09-17 23:28 UTC, pedronunes19 commented
> > The profile picture request is returning a 404, although the picture is correctly stored locally.
> 
> Have you run `php artisan storage:link`?

I hadn't, thank you

2023-09-19 00:53 UTC, ttoino commented on resources/js/Components/Profile/CvArea.vue
> +                    </svg>
Doing this will no longer be necessary after #81

2023-09-19 00:57 UTC, pedronunes19 commented on resources/js/Components/Profile/CvArea.vue
> +                    </svg>
:boom:

2023-09-22 16:30 UTC, Naapperas commented on app/Http/Controllers/CVController.php
> +        Participant::where('user_id', $request->user()->id)->first()->deleteCV();
Ideally this should use the `usertype` attribute.

2023-09-22 16:37 UTC, Naapperas commented on app/Models/VisitHistory.php
With the cock

2023-09-22 16:37 UTC, Naapperas commented on app/Providers/AuthServiceProvider.php
> +        Gate::define('view_participant', fn ($user, Participant $participant) => ($user->id == $participant->user_id) || (($user->usertype_type == Company::class) && VisitHistory::where('company_id',
Cock this.

2023-09-22 16:39 UTC, Naapperas commented on resources/js/Components/Profile/CvArea.vue
> +    console.log(cvInput.value?.files?.[0]);
BRuh

2023-09-22 16:40 UTC, Naapperas commented on resources/js/Components/Profile/CvArea.vue
> +            onSuccess: () => clearCVFileInput,
Fix

2023-09-22 16:45 UTC, Naapperas requested changes
Sorry

2023-09-22 16:45 UTC, Naapperas commented on resources/js/Pages/Profile/Show.vue
> +        <main class="flex flex-col items-center bg-2023-bg pt-6 sm:pt-0">
template

2023-09-22 21:46 UTC, pedronunes19 commented on app/Http/Controllers/CVController.php
> +        Participant::where('user_id', $request->user()->id)->first()->deleteCV();
I know

2023-09-22 21:48 UTC, pedronunes19 commented on resources/js/Components/Profile/CvArea.vue
> +            onSuccess: () => clearCVFileInput,
fixed

2023-09-22 21:49 UTC, pedronunes19 commented on resources/js/Pages/Profile/Show.vue
> +        <main class="flex flex-col items-center bg-2023-bg pt-6 sm:pt-0">
div

2023-09-22 23:00 UTC, toni-santos approved these changes

2023-09-22 23:25 UTC, Naapperas approved these changes

2023-09-22 23:26 UTC, merged