Teams backend
semanadeinformatica/website pull request #68
Opened 2023-09-15 23:17 UTC by toni-santos

Closes #61

2023-09-16 00:04 UTC, ttoino requested changes

2023-09-16 00:04 UTC, ttoino commented on database/migrations/2023_09_15_133618_create_departments_table.php
> +        Schema::dropIfExists('teams');
You should drop departments and staff, not this table.

2023-09-16 00:04 UTC, ttoino commented on app/Models/Student.php
> +    }
I think this should be a hasMany relationship

2023-09-16 00:04 UTC, ttoino commented on app/Models/Staff.php
> +    }
This should be a belongsTo relationship

2023-09-16 00:04 UTC, ttoino commented on app/Http/Controllers/StaffCRUDController.php
> +        'department_id' => 'required|integer',
These should validate against the relevant tables. I can't remember the syntax off the top of my head but it's something like `exists:students,id`

2023-09-16 00:04 UTC, ttoino commented on app/Http/Controllers/StaffCRUDController.php
> +    }
These functions are not needed if you're not doing something more advanced

2023-09-16 00:04 UTC, ttoino commented on app/Http/Controllers/DepartmentCRUDController.php
> +    }
Same as above

2023-09-16 00:04 UTC, ttoino commented on resources/js/Pages/CRUD/Department/Create.vue
> +        </form>
I'd prefer name to be first, but it's just a nitpick

2023-09-16 00:04 UTC, ttoino commented on resources/js/Pages/CRUD/Department/Edit.vue
> +        </form>
Same as above

2023-09-16 00:04 UTC, ttoino commented on resources/js/Types/Department.ts
> +    id: number;
`id` is redundant here, `Model` already provides it

2023-09-16 00:04 UTC, ttoino commented on resources/js/Types/Staff.ts
> +    id: number;
Same as above

2023-09-16 16:06 UTC, ttoino requested changes

2023-09-16 16:06 UTC, ttoino commented on app/Models/Edition.php
> +    public function team(): HasMany
This should be `departments`, and use the `Department` class

2023-09-16 16:06 UTC, ttoino commented on app/Models/Staff.php
> +    public function team(): BelongsTo
This should be `department`

2023-09-16 16:06 UTC, ttoino commented on resources/js/Pages/CRUD/Staff/Create.vue
> +                    {{ `${student.user?.name} - ${student.user?.id}` }}
You don't need to use string interpolation here

```suggestion
                    {{ student.user?.name }} - {{ student.user?.id }}
```

2023-09-16 16:06 UTC, ttoino commented on resources/js/Pages/CRUD/Staff/Edit.vue
> +                    {{ `${student.user?.name} - ${student.user?.id}` }}
Same as above

2023-09-17 00:30 UTC, Naapperas requested changes

2023-09-17 00:30 UTC, Naapperas commented on app/Models/Department.php
> +    public function department(): BelongsTo
```suggestion
    public function edition(): BelongsTo
```

2023-09-17 01:38 UTC, ttoino requested changes

2023-09-17 01:38 UTC, ttoino commented on resources/js/Pages/CRUD/Staff/Create.vue
> +                    }}
You don't need string interpolation here

2023-09-17 01:38 UTC, ttoino commented on resources/js/Pages/CRUD/Staff/Edit.vue
> +                    }}
Same as above

2023-09-17 01:38 UTC, ttoino commented on app/Models/Edition.php
> +    }
Same as last review

2023-09-17 13:35 UTC, ttoino approved these changes, later dismissed

2023-09-17 14:38 UTC, Naapperas submitted a review, later dismissed

2023-09-17 14:59 UTC, Naapperas approved these changes

2023-09-17 15:08 UTC, ttoino approved these changes

2023-09-17 15:16 UTC, merged