Events page
semanadeinformatica/website pull request #70
Opened 2023-09-16 03:18 UTC by toni-santos

Closes #56

2023-09-17 00:33 UTC, Naapperas submitted a review, later dismissed

2023-09-22 11:23 UTC, pedronunes19 requested changes

2023-09-22 11:23 UTC, pedronunes19 commented on resources/js/Pages/Event.vue
> +                <span class="text-base">{{ event.capacity }} lugares</span>
add v-if="event.capacity"

2023-09-22 11:28 UTC, pedronunes19 approved these changes

2023-09-22 18:38 UTC, ttoino approved these changes

2023-09-22 18:43 UTC, merged