Landing page for admins
semanadeinformatica/website pull request #78
Opened 2023-09-18 00:53 UTC by toni-santos

Closes #73

2023-09-18 01:06 UTC, ttoino requested changes

2023-09-18 01:06 UTC, ttoino commented on resources/js/Pages/Admin.vue
> +    },
These should probably be in portuguese

2023-09-18 01:06 UTC, ttoino commented on routes/web.php
> +                Route::name('index')->get('/index', function () {
I'd prefer `/`

2023-09-18 10:29 UTC, pedrosilva17 commented
Agree with João's observations. Other than that, useful landing page 👍

2023-09-18 11:32 UTC, pedrosilva17 commented
I just remembered, maybe we should have a section for managing enrollments? We could change the amount of points of a participant in case a problem arises, just in case

2023-09-19 00:48 UTC, ttoino approved these changes

2023-09-19 09:58 UTC, Naapperas approved these changes

2023-09-19 11:25 UTC, merged