Added competition info
semanadeinformatica/website pull request #79
Opened 2023-09-18 01:10 UTC by Naapperas

2023-09-19 22:44 UTC, diogofonte commented on resources/js/Pages/CRUD/Competition/Edit.vue
> +    <CardLayout title="Criar Competição">
Shouldn't it be "Edit Competition"?

2023-09-20 14:37 UTC, toni-santos commented
Inputing a end date earlier than the start date is possible, this shouldn't be the case

2023-09-21 16:03 UTC, pedronunes19 approved these changes, later dismissed

2023-09-21 18:16 UTC, ttoino requested changes

2023-09-21 18:16 UTC, ttoino commented on database/helpers.php
> +    $model2 = $models[1];
You can use array destructuring for this

2023-09-21 18:16 UTC, ttoino commented on database/helpers.php
> +    }
Why is this needed?

2023-09-21 18:16 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Create.vue
> +            </select>
We should use the new TextInput[type=select]

2023-09-21 18:16 UTC, ttoino commented on resources/js/Pages/CRUD/Competition/Edit.vue
> +            </select>
Same as above

2023-09-21 18:16 UTC, ttoino commented on resources/js/Pages/CRUD/CompetitionTeam/Create.vue
> +            </select>
Same as above

2023-09-21 18:16 UTC, ttoino commented on resources/js/Pages/CRUD/CompetitionTeam/Edit.vue
> +            </select>
Same as above

2023-09-21 18:16 UTC, ttoino commented on resources/js/Pages/CRUD/CompetitionTeam/Index.vue
> +                <Header>Pontos</Header>
Careful with the Header attributes

2023-09-21 18:16 UTC, ttoino commented on resources/js/Types/Competition.ts
> +    date_end: Date;
This should not be Date, the data that comes from the server is just a string

2023-09-21 18:22 UTC, toni-santos submitted a review, later dismissed

2023-09-21 18:54 UTC, Naapperas commented on database/helpers.php
> +    }
I just took this from the Laravel source code, even though I believe we will never _not_ use the `model::class` syntax this is a safety measure.

2023-09-21 18:55 UTC, Naapperas commented on resources/js/Pages/CRUD/Competition/Create.vue
> +            </select>
This was made before that change, nice catch.

2023-09-21 20:01 UTC, ttoino approved these changes

2023-09-21 20:14 UTC, toni-santos approved these changes

2023-09-21 20:17 UTC, merged