Enrollment CRUD and admin pages
semanadeinformatica/website pull request #83
Opened 2023-09-18 21:24 UTC by pedrosilva17

Closes #82
Implements CRUD for enrollments and admin pages to manage them.

2023-09-19 00:44 UTC, ttoino requested changes

2023-09-19 00:44 UTC, ttoino commented on app/Http/Controllers/EnrollmentCRUDController.php
> +        'points' => 'required|integer',
A user's points are calculated automatically, they shouldn't be editable.

2023-09-22 22:55 UTC, toni-santos approved these changes, later dismissed

2023-09-22 23:54 UTC, Naapperas requested changes

2023-09-22 23:54 UTC, Naapperas commented on resources/js/Pages/CRUD/Enrollment/Create.vue
> +            </select>
Use the new TextInput type `select`: there are already examples in place using that component.

2023-09-22 23:54 UTC, Naapperas commented on resources/js/Pages/CRUD/Enrollment/Edit.vue
> +
Same as above.

2023-09-22 23:54 UTC, Naapperas commented on resources/js/Pages/CRUD/Enrollment/Index.vue
> +                <Header sort-by="edition_id">Nome da Edição</Header>
Change this to a `filter-by`.

2023-09-23 01:06 UTC, Naapperas approved these changes

2023-09-23 01:07 UTC, ttoino approved these changes

2023-09-23 01:09 UTC, merged