changes all occurrences of Student to Participant
semanadeinformatica/website pull request #84
Opened 2023-09-18 22:08 UTC by diogofonte

Closes #80

2023-09-18 22:19 UTC, pedrosilva17 requested changes

2023-09-18 22:19 UTC, pedrosilva17 commented on database/factories/StudentFactory.php
> +class ParticipantFactory extends Factory
The file name should also be `ParticipantFactory.php`, you forgot to change it.

2023-09-18 22:22 UTC, diogofonte commented on database/factories/StudentFactory.php
> +class ParticipantFactory extends Factory
I forgot that, thank you

2023-09-18 22:40 UTC, pedrosilva17 commented on resources/js/messages.ts
> +                "A Semana de Informática (SINF), organizada pelo Núcleo de Informática da Associação de Estudantes da Faculdade de Engenharia da Universidade do Porto (NIAEFEUP), foi criada com o int
```suggestion
                "A Semana de Informática (SINF), organizada pelo Núcleo de Informática da Associação de Estudantes da Faculdade de Engenharia da Universidade do Porto (NIAEFEUP), foi criada com o intuito de permitir aos participantes desenvolver as suas capacidades nas diversas áreas da Informática, promovendo a sua interação com o mundo empresarial através de eventos sociais.",
```
Also, if we don't want to imply that this event is only for students, we should remove the segments from the about us section that say "no matter the course".

2023-09-18 22:41 UTC, pedrosilva17 commented on resources/js/messages.ts
> +                "A Semana de Informática (SINF), organizada pelo Núcleo de Informática da Associação de Estudantes da Faculdade de Engenharia da Universidade do Porto (NIAEFEUP), foi criada com o int
Not sure what everyone else thinks about this, though

2023-09-18 22:43 UTC, diogofonte commented on resources/js/messages.ts
> +                "A Semana de Informática (SINF), organizada pelo Núcleo de Informática da Associação de Estudantes da Faculdade de Engenharia da Universidade do Porto (NIAEFEUP), foi criada com o int
I forgot to ask about that, just changing "estudantes" to "partipantes" sounds weird. I'm going to change that and also the name of one of the migrations

2023-09-19 00:59 UTC, ttoino requested changes

2023-09-19 00:59 UTC, ttoino commented on resources/js/messages.ts
> +                "A Semana de Informática (SINF), organizada pelo Núcleo de Informática da Associação de Estudantes da Faculdade de Engenharia da Universidade do Porto (NIAEFEUP), foi criada com o int
This comma feels weird now

```suggestion
                "A Semana de Informática (SINF), organizada pelo Núcleo de Informática da Associação de Estudantes da Faculdade de Engenharia da Universidade do Porto (NIAEFEUP), foi criada com o intuito de permitir aos participantes desenvolver as suas capacidades nas diversas áreas da Informática, promovendo a sua interação com o mundo empresarial através de eventos sociais.",
```

2023-09-19 00:59 UTC, ttoino commented on database/migrations/2023_07_04_010134_create_schema.php
While I'm usually iffy about editing migrations, since the website is not yet live, and due to the scale of this change, I think it's warranted this time.

2023-09-19 00:59 UTC, ttoino commented on database/factories/CompanyFactory.php
> + * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Participant>
This should have been `Company`

2023-09-19 00:59 UTC, ttoino commented on database/factories/AdminFactory.php
> + * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Participant>
This should have been `Admin`

2023-09-19 09:15 UTC, ttoino approved these changes

2023-09-19 09:17 UTC, pedrosilva17 approved these changes

2023-09-19 09:25 UTC, merged