added minimal things to company page
semanadeinformatica/website pull request #88
Opened 2023-09-19 16:37 UTC by CiscoPr

2023-09-22 10:19 UTC, ttoino commented
Ideally this would use the same page as in #48.

2023-09-22 15:08 UTC, CiscoPr commented
> Ideally this would use the same route as in #48.

Yeah, i will refactor that

2023-09-24 14:01 UTC, Naapperas commented
Don't forget to format the code

2023-09-25 16:48 UTC, pedronunes19 requested changes

2023-09-25 16:48 UTC, pedronunes19 commented on resources/js/Pages/Profile/Show.vue
> +                />
this should only appear when either user.usertype_type is Participant (if it exists) or the auth user is Participant

2023-09-26 06:42 UTC, CiscoPr commented on resources/js/Pages/Profile/Show.vue
> +                />
yeah, i forgot some cases of this condition, ty

2023-09-28 01:58 UTC, Naapperas commented
What is missing? The student visit history?

2023-09-28 10:17 UTC, CiscoPr commented
> What is missing? The student visit history?

are you talking about the table?

2023-09-28 10:23 UTC, Naapperas commented
> > What is missing? The student visit history?
> 
> are you talking about the table?

I'm talking about what features or fixes are missing for this PR to be merged.

2023-09-28 10:31 UTC, CiscoPr commented
> > > What is missing? The student visit history?
> > 
> > 
> > are you talking about the table?
> 
> I'm talking about what features or fixes are missing for this PR to be merged.

what is missing is to get the participants... the relationship as it is for now always returns an undefined array

2023-09-28 11:29 UTC, Naapperas commented
> > > > What is missing? The student visit history?
> > > 
> > > 
> > > are you talking about the table?
> > 
> > 
> > I'm talking about what features or fixes are missing for this PR to be merged.
> 
> what is missing is to get the participants correctly... the relationship as it is for now always returns an undefined array

Due to the way quests are linked to stands, we may need more complex logic that just having a deep query.

At what point does the query fail? That's the point where we need to act upon.

2023-09-30 16:37 UTC, pedronunes19 commented on resources/js/Pages/Profile/Show.vue
> +    participants: Participant[];
I don't think this prop is being passed when we use the default route from jetstream, that's likely why it's always undefined (one of the reasons at least)

2023-09-30 17:38 UTC, CiscoPr commented on resources/js/Pages/Profile/Show.vue
> +    participants: Participant[];
You made a good point. However, i already had noted that... i just forgot to push :,))
And yet again, this doesn't solve the problem

2023-10-12 15:08 UTC, toni-santos commented on app/Http/Controllers/UserController.php
> +                return redirect()->route('profile.show')->dangerBanner('Não tens acesso a esta página.');
Why do this instead of just showing 403?

2023-10-12 15:08 UTC, toni-santos commented on app/Providers/AuthServiceProvider.php
> +                ! $cv_user->isAdmin()
What do you mean by "that do not belong to admins"?

2023-10-12 15:12 UTC, Naapperas commented on app/Http/Controllers/UserController.php
> +                return redirect()->route('profile.show')->dangerBanner('Não tens acesso a esta página.');
:boom: error page :boom:

2023-10-12 15:16 UTC, Naapperas commented on app/Providers/AuthServiceProvider.php
> +                ! $cv_user->isAdmin()
Perhaps my wording was off here: this was just a way of securing this validation agains an admin trying to view another admin's profile.

2023-10-12 16:26 UTC, CiscoPr commented
we should be careful, because, when clicking on this on a student profile as a company, it will return this error:
![image](https://github.com/semanadeinformatica/website-2023/assets/79597450/0120ef1a-7307-45a9-b70b-ff0f6fa5aa27)
![image](https://github.com/semanadeinformatica/website-2023/assets/79597450/2188c08b-1e77-4da7-88c6-017b7739dd2a)

2023-10-12 16:28 UTC, CiscoPr commented
on another note, we should also increase the width of this CV button in the same situation (company visiting enrolled student page)

2023-10-12 16:32 UTC, CiscoPr commented
Finally, i think we should also decrease the size of the "no students enrolled yet" message. Imo, it's too big

2023-10-12 16:45 UTC, pedronunes19 commented
> we should be careful, because, when clicking on this on a student profile as a company, it will return this error: ![image](https://user-images.githubusercontent.com/79597450/274666274-0120ef1a-7307-45a9-b70b-ff0f6fa5aa27.png) ![image](https://user-images.githubusercontent.com/79597450/274666339-2188c08b-1e77-4da7-88c6-017b7739dd2a.png)

Why can a company even see this?

2023-10-12 17:21 UTC, Naapperas commented
> > we should be careful, because, when clicking on this on a student profile as a company, it will return this error: ![image](https://user-images.githubusercontent.com/79597450/274666274-0120ef1a-7307-45a9-b70b-ff0f6fa5aa27.png) ![image](https://user-images.githubusercontent.com/79597450/274666339-2188c08b-1e77-4da7-88c6-017b7739dd2a.png)
> 
> Why can a company even see this?

I believe companies should at least be able what events the user has joined that may be related to them

2023-10-13 20:06 UTC, Naapperas commented on app/Http/Controllers/UserController.php
> +                return redirect()->route('profile.show')->dangerBanner('Não tens acesso a esta página.');
I'm marking this as resolved but if you feel that this should be changed go ahead.

2023-10-13 23:43 UTC, pedronunes19 submitted a review, later dismissed

2023-10-15 21:52 UTC, Naapperas approved these changes, later dismissed

2023-10-15 22:39 UTC, toni-santos approved these changes, later dismissed

2023-10-16 16:41 UTC, pedronunes19 approved these changes

2023-10-16 16:41 UTC, ttoino approved these changes

2023-10-16 16:47 UTC, merged